/**
 * Data access for posts — the ONLY place that knows about norm and the
 * storage shape (tags as JSON text, `createdAt` as a `Date`). Modules
 * depend on this, not on norm, so they stay persistence-agnostic and
 * unit-testable against a fake repository.
 *
 * @module
 */

import type { BlogDb } from '../db.ts';
import type { Post } from '../types.ts';

/** A stored posts row as norm hands it back. */
type PostRow = {
  id: string;
  title: string;
  body: string;
  tags: string;
  published: boolean;
  createdAt: Date | string;
};

/** Options for a paged, optionally-filtered listing. */
export type ListPostsOptions = {
  published?: boolean;
  limit: number;
  offset: number;
};

export class PostRepository {
  constructor(private readonly db: BlogDb) {}

  private get repo() {
    return this.db.repo('Posts');
  }

  /** Map a stored row to the domain shape (tags parsed, date normalized). */
  private toPost(row: PostRow): Post {
    return {
      id: row.id,
      title: row.title,
      body: row.body,
      tags: JSON.parse(row.tags) as string[],
      published: Boolean(row.published),
      createdAt: new Date(row.createdAt).toISOString(),
    };
  }

  /** A page of posts (newest first) plus the total matching count. */
  async list(
    opts: ListPostsOptions,
  ): Promise<{ rows: Post[]; total: number }> {
    const filter = opts.published === undefined
      ? undefined
      : { '@published': opts.published };
    // deno-lint-ignore no-explicit-any
    const found = await this.repo.find(filter as any, {
      orderBy: { '@createdAt': 'DESC' },
      limit: opts.limit,
      offset: opts.offset,
    });
    // deno-lint-ignore no-explicit-any
    const counted = await this.repo.count(filter as any);
    return {
      rows: (found.data as PostRow[]).map((r) => this.toPost(r)),
      total: counted.count,
    };
  }

  /** One post by id, or `undefined`. */
  async get(id: string): Promise<Post | undefined> {
    const res = await this.repo.find({ '@id': id });
    const row = res.data[0] as PostRow | undefined;
    return row === undefined ? undefined : this.toPost(row);
  }

  /** Insert a post; the UUID id and `createdAt` are generated by norm. */
  async create(
    input: { title: string; body: string; tags?: string[] },
  ): Promise<Post> {
    const res = await this.repo.insert({
      title: input.title,
      body: input.body,
      tags: JSON.stringify(input.tags ?? []),
    });
    return this.toPost(res.data[0] as PostRow);
  }

  /** Patch a post; returns the fresh row, or `undefined` if it's gone. */
  async update(
    id: string,
    patch: {
      title?: string;
      body?: string;
      published?: boolean;
      tags?: string[];
    },
  ): Promise<Post | undefined> {
    if (await this.get(id) === undefined) return undefined;
    const set: Record<string, unknown> = {};
    if (patch.title !== undefined) set.title = patch.title;
    if (patch.body !== undefined) set.body = patch.body;
    if (patch.published !== undefined) set.published = patch.published;
    if (patch.tags !== undefined) set.tags = JSON.stringify(patch.tags);
    // deno-lint-ignore no-explicit-any
    await this.repo.update(set as any, { '@id': id } as any);
    return this.get(id);
  }

  /** Delete a post (its comments cascade at the database). */
  async remove(id: string): Promise<boolean> {
    if (await this.get(id) === undefined) return false;
    await this.repo.delete({ '@id': id });
    return true;
  }

  /** Total number of posts. */
  async count(): Promise<number> {
    const res = await this.repo.count();
    return res.count;
  }

  /** Seed two posts on first run so the demo has something to show. */
  async seedIfEmpty(): Promise<void> {
    if (await this.count() > 0) return;
    await this.create({
      title: 'Welcome',
      body: 'First post on the blog.',
      tags: ['meta'],
    });
    await this.create({
      title: 'Draft in progress',
      body: 'Not ready yet.',
    });
  }
}
