/**
 * @fileoverview `@tundralibs/rapid` — a config-driven application
 * framework for Deno, Bun, Node and Cloudflare Workers: HTTP routes,
 * WebSocket commands and cron jobs behind one middleware onion, declared
 * as functions or as decorated modules, with an HTML-over-the-wire UI
 * layer, native observability (slogger always on, tracer opt-in) and
 * the `@tundralibs/pact` adapter for authentication.
 *
 * @module
 */

export { Application } from './Application.ts';
export {
  Context,
  HTTPContext,
  type HTTPContextInit,
  JOBContext,
  type JOBContextInit,
  type JobTick,
  type SOCKETConnection,
  SOCKETContext,
  type SOCKETContextInit,
} from './context/mod.ts';
export {
  auth,
  config,
  connection,
  cookie,
  decorationsOf,
  DELETE,
  GET,
  header,
  JOB,
  type JobDecoratorOptions,
  Module,
  type ModuleDecoratorOptions,
  moduleMetaOf,
  type ModuleMountOptions,
  On,
  paging,
  param,
  PATCH,
  payload,
  POST,
  PUT,
  query,
  type RouteDecoratorOptions,
  SOCKET,
  type SocketDecoratorOptions,
  Use,
} from './decorators/mod.ts';
export {
  asValidationError,
  RAPID_ERROR_CODES,
  RapidError,
  type RapidErrorCode,
  type RapidErrorMeta,
} from './errors/mod.ts';
export { validated } from './utils/validated.ts';
export {
  event,
  EventContext,
  initModules,
  InvokeContext,
  ModuleRuntime,
  RapidModule,
  type RapidModuleLifecycle,
  Reply,
  reply,
} from './modules/mod.ts';
export {
  compress,
  type CompressOptions,
  cors,
  type CorsOptions,
  csrf,
  type CsrfOptions,
  etag,
  getSession,
  guardHTTP,
  guardJOB,
  guardSOCKET,
  idempotency,
  type IdempotencyHooks,
  type IdempotencyOptions,
  type IdempotencyRecord,
  type IdempotentReply,
  markStateKeyUser,
  memoryIdempotencyHooks,
  memoryRateLimitHooks,
  memorySessionHooks,
  MIDDLEWARE_SCOPE,
  MIDDLEWARE_STATE_KEY,
  middlewareScope,
  middlewareUsesStateKey,
  onlyApi,
  onlyHTTP,
  onlyJOB,
  onlySOCKET,
  onlyUi,
  type RapidSession,
  rateLimit,
  type RateLimitHooks,
  type RateLimitOptions,
  type RateLimitWindow,
  secureHeaders,
  type SecureHeadersOptions,
  session,
  type SessionData,
  type SessionHooks,
  type SessionOptions,
  type SessionRecord,
  timeout,
} from './middlewares/mod.ts';
export type {
  RapidAccessLogOptions,
  RapidApplicationEvents,
  RapidApplicationExporterConfig,
  RapidApplicationFactoryOptions,
  RapidApplicationFetchInfo,
  RapidApplicationHeaderOptions,
  RapidApplicationJobMetrics,
  RapidApplicationJobsOptions,
  RapidApplicationOptions,
  RapidApplicationPagingOptions,
  RapidApplicationQueryOptions,
  RapidApplicationServerOptions,
  RapidApplicationStaticConfig,
  RapidApplicationStaticEntry,
  RapidApplicationUploadOptions,
  RapidBinder,
  RapidBinderSource,
  RapidBinds,
  RapidChannelOptions,
  RapidClusterMember,
  RapidClusterSnapshot,
  RapidContext,
  RapidContextArgs,
  RapidContextPaging,
  RapidContextQuery,
  RapidContextQueryFilter,
  RapidContextQuerySort,
  RapidContextResponse,
  RapidContextState,
  RapidContextSurface,
  RapidContextType,
  RapidCoreData,
  RapidDecoration,
  RapidErrorHandler,
  RapidErrorTemplates,
  RapidHTTPHandler,
  RapidHTTPMiddleware,
  RapidHTTPRequestBody,
  RapidJobEntry,
  RapidJOBHandler,
  RapidMiddleware,
  RapidModuleMeta,
  RapidModuleReply,
  RapidRouteEntry,
  RapidRouteOpenApi,
  RapidRouteOptions,
  RapidRouteTemplate,
  RapidSchema,
  RapidSocketEntry,
  RapidSOCKETHandler,
  RapidSOCKETMiddleware,
  RapidTemplate,
  RapidUiConfigOptions,
  RapidUiOptions,
  RapidUiTemplateOptions,
  RapidUploadedFile,
  RapidView,
} from './types/mod.ts';
export type {
  RapidModuleClass,
  RapidModuleContext,
  RapidModuleEventMap,
  RapidModuleEventPayload,
  RapidModuleEventsOf,
  RapidModuleInitOptions,
  RapidModuleInitResult,
  RapidModuleInstances,
  RapidModuleInstancesOf,
  RapidModuleInvokeMiddleware,
  RapidModuleInvokeResult,
  RapidModuleInvokeResultOf,
  RapidModuleInvokeSeed,
  RapidModuleMethodDecorator,
  RapidModuleMethodKeys,
  RapidModulePayload,
  RapidModulePayloadOf,
  RapidModuleSources,
} from './types/mod.ts';
