/**
 * @fileoverview `@tundralibs/rapid` — a config-driven API framework for
 * Deno, Bun, and Node. Phase 1 assembles an application from FUNCTIONS
 * (Oak-style route/middleware/job registration) with native
 * observability (slogger always on, tracer opt-in) and a
 * cronus-scheduled job transport.
 *
 * @module
 */

export { Application } from './Application.ts';
export {
  Context,
  HTTPContext,
  type HTTPContextInit,
  JOBContext,
  type JOBContextInit,
  type JobTick,
  type SOCKETConnection,
  SOCKETContext,
  type SOCKETContextInit,
} from './context/mod.ts';
export {
  connection,
  decorationsOf,
  DELETE,
  GET,
  header,
  JOB,
  type JobDecoratorOptions,
  Module,
  type ModuleDecoratorOptions,
  moduleMetaOf,
  type ModuleMountOptions,
  On,
  paging,
  param,
  PATCH,
  payload,
  POST,
  PUT,
  query,
  type RouteDecoratorOptions,
  SOCKET,
  type SocketDecoratorOptions,
  Use,
} from './decorators/mod.ts';
export {
  RAPID_ERROR_CODES,
  RapidError,
  type RapidErrorCode,
  type RapidErrorMeta,
} from './errors/mod.ts';
export { validated } from './utils/validated.ts';
export {
  event,
  EventContext,
  initModules,
  InvokeContext,
  ModuleRuntime,
  RapidModule,
  type RapidModuleLifecycle,
  Reply,
  reply,
} from './modules/mod.ts';
export {
  type AuthBag,
  authenticate,
  type AuthenticateOptions,
  authorize,
  compress,
  type CompressOptions,
  cors,
  type CorsOptions,
  csrf,
  type CsrfOptions,
  etag,
  getSession,
  guardHTTP,
  guardJOB,
  guardSOCKET,
  healthCheck,
  type HealthCheckOptions,
  idempotency,
  type IdempotencyOptions,
  type IdempotencyRecord,
  type IdempotentReply,
  markStateKeyUser,
  memoryStore,
  type MemoryStoreOptions,
  MIDDLEWARE_SCOPE,
  MIDDLEWARE_STATE_KEY,
  middlewareScope,
  middlewareUsesStateKey,
  onlyHTTP,
  onlyJOB,
  onlySOCKET,
  type RapidSession,
  rateLimit,
  type RateLimitOptions,
  requestId,
  type RequestIdOptions,
  requestLogger,
  type RequestLoggerOptions,
  responseTimer,
  type ResponseTimerOptions,
  secureHeaders,
  type SecureHeadersOptions,
  session,
  type SessionData,
  type SessionOptions,
  type Store,
  timeout,
} from './middlewares/mod.ts';
export type {
  RapidApplicationEvents,
  RapidApplicationExporterConfig,
  RapidApplicationFactoryOptions,
  RapidApplicationFetchInfo,
  RapidApplicationJobMetrics,
  RapidApplicationJobsOptions,
  RapidApplicationOptions,
  RapidApplicationPagingOptions,
  RapidApplicationQueryOptions,
  RapidApplicationServerOptions,
  RapidApplicationStaticConfig,
  RapidApplicationStaticEntry,
  RapidApplicationUploadOptions,
  RapidBinder,
  RapidBinderSource,
  RapidBinds,
  RapidChannelOptions,
  RapidClusterMember,
  RapidClusterSnapshot,
  RapidContext,
  RapidContextArgs,
  RapidContextPaging,
  RapidContextQuery,
  RapidContextQueryFilter,
  RapidContextQuerySort,
  RapidContextResponse,
  RapidContextState,
  RapidContextType,
  RapidCoreData,
  RapidDecoration,
  RapidErrorHandler,
  RapidErrorTemplates,
  RapidHTTPHandler,
  RapidHTTPMiddleware,
  RapidHTTPRequestBody,
  RapidJobEntry,
  RapidJOBHandler,
  RapidMiddleware,
  RapidModuleMeta,
  RapidModuleReply,
  RapidRouteEntry,
  RapidRouteOpenApi,
  RapidRouteOptions,
  RapidRouteTemplate,
  RapidSocketEntry,
  RapidSOCKETHandler,
  RapidSOCKETMiddleware,
  RapidTemplate,
  RapidUiConfigOptions,
  RapidUiOptions,
  RapidUiTemplateOptions,
  RapidUploadedFile,
  RapidView,
} from './types/mod.ts';
export type {
  RapidModuleClass,
  RapidModuleContext,
  RapidModuleEventMap,
  RapidModuleEventPayload,
  RapidModuleEventsOf,
  RapidModuleInitOptions,
  RapidModuleInitResult,
  RapidModuleInstances,
  RapidModuleInstancesOf,
  RapidModuleInvokeMiddleware,
  RapidModuleInvokeResult,
  RapidModuleInvokeResultOf,
  RapidModuleInvokeSeed,
  RapidModuleMethodDecorator,
  RapidModuleMethodKeys,
  RapidModulePayload,
  RapidModulePayloadOf,
  RapidModuleSources,
} from './types/mod.ts';
