/**
 * String Expression Validators
 *
 * This module provides validation functions for string manipulation expressions in OQL.
 * It includes assertion and type guard functions for various string operations:
 * - UUID: Generate UUID v4
 * - CONCAT: Concatenate multiple strings
 * - LOWER: Convert to lowercase
 * - UPPER: Convert to uppercase
 * - TRIM: Remove leading and trailing whitespace
 * - LTRIM: Remove leading whitespace only
 * - RTRIM: Remove trailing whitespace only
 * - SUBSTR: Extract substring
 * - REPLACE: Replace string occurrences
 * - LPAD: Left pad string to specified length
 * - RPAD: Right pad string to specified length
 * - ENCRYPT: Symmetric encryption (database-specific)
 * - DECRYPT: Symmetric decryption (database-specific)
 *
 * @module asserts/Expressions/String
 */

import { isColumnIdentifier } from '../columnIdentifier.ts';
import type { Expressions, StringExpressions } from '../../types/mod.ts';
import { assertBaseExpression } from './base.ts';

/**
 * Helper function to validate a single string argument expression.
 * Used by LOWER, UPPER, TRIM, LTRIM, RTRIM which all have the same structure.
 *
 * @param x - The expression to validate
 * @param type - The expression type name
 * @param columnList - Optional list of valid column names (without '@' prefix)
 * @throws {TypeError} If the expression structure is invalid
 * @internal
 */
const assertSingleArgStringExpression = (
  x: unknown,
  type: string,
  columnList?: string[],
): void => {
  assertBaseExpression(x, type);
  if (!('args' in x)) {
    throw new TypeError(
      `Invalid Expression definition: Missing 'args' property for ${type} expression`,
    );
  }
  // Known column reference is fine; otherwise the arg must be a string
  // literal. @-strings that aren't in the list fall through and are
  // accepted as literals.
  if (isColumnIdentifier(x.args, columnList)) return;
  if (typeof x.args !== 'string') {
    throw new TypeError(
      `Invalid Expression definition: Invalid 'args' property in ${type} expression`,
    );
  }
};

/**
 * Validate a string argument: either a string literal or a column ref.
 * Used by every string expression's argument validation.
 *
 * @internal
 */
const validateStringArg = (
  arg: unknown,
  argName: string,
  expressionType: string,
  columnList?: string[],
): void => {
  // Known column reference: accept and return.
  if (isColumnIdentifier(arg, columnList)) return;
  // Otherwise must be a string literal (which includes @-strings that
  // aren't recognized column refs — they're treated as literals here).
  if (typeof arg !== 'string') {
    throw new TypeError(
      `Invalid Expression definition: ${argName} must be a string or ` +
        `column identifier in ${expressionType} expression, got ${typeof arg}`,
    );
  }
};

/**
 * Validate a number argument that must be a literal — used for SUBSTR
 * start/length, LPAD/RPAD length etc. Column references are allowed; nested
 * numeric expressions are NOT (use {@link validateExprArg} from
 * Numeric.ts for those contexts).
 *
 * @internal
 */
const validateNumberArg = (
  arg: unknown,
  argName: string,
  expressionType: string,
  columnList?: string[],
): void => {
  // Known column reference: accept.
  if (isColumnIdentifier(arg, columnList)) return;
  // Otherwise must be a number literal — strings (including @-strings
  // not in the list, which are now literals) are not allowed in number
  // positions.
  if (typeof arg === 'string') {
    throw new TypeError(
      `Invalid Expression definition: ${argName} must be a number or ` +
        `column identifier in ${expressionType} expression, got string literal`,
    );
  }
  if (typeof arg !== 'number') {
    throw new TypeError(
      `Invalid Expression definition: ${argName} must be a number or ` +
        `column identifier in ${expressionType} expression, got ${typeof arg}`,
    );
  }
};

/**
 * Asserts that a value is a valid UUID expression.
 *
 * The UUID expression generates a UUID v4. For databases that don't support
 * native UUID generation (SQLite, MongoDB), the UUID is generated by DAM before
 * query execution.
 *
 * @param x - The value to validate
 * @throws {TypeError} If the value is not a valid UUID expression
 *
 * @example
 * ```ts
 * const expr = { $$_expression: 'UUID' };
 * assertUUIDExpression(expr);
 * ```
 */
export const assertUUIDExpression: (
  x: unknown,
) => asserts x is Extract<Expressions, { $$_expression: 'UUID' }> = (
  x: unknown,
): asserts x is Extract<Expressions, { $$_expression: 'UUID' }> => {
  assertBaseExpression(x, 'UUID');
};

/**
 * Type guard to check if a value is a valid UUID expression.
 *
 * @param x - The value to check
 * @returns `true` if the value is a valid UUID expression, `false` otherwise
 *
 * @example
 * ```ts
 * declare function getExpression(): unknown;
 *
 * const expr = { $$_expression: 'UUID' };
 * if (isUUIDExpression(expr)) {
 *   // expr is narrowed to Extract<Expressions, { $$_expression: 'UUID' }>
 *   console.log('Will generate a UUID v4');
 * }
 *
 * // Validate user input
 * const userExpr: unknown = getExpression();
 * if (isUUIDExpression(userExpr)) {
 *   console.log('Valid UUID generator expression');
 * }
 * ```
 */
export const isUUIDExpression = (
  x: unknown,
): x is Extract<Expressions, { $$_expression: 'UUID' }> => {
  try {
    assertUUIDExpression(x);
    return true;
  } catch {
    return false;
  }
};

/**
 * Asserts that a value is a valid CONCAT expression.
 *
 * The CONCAT expression joins multiple strings together. It accepts an array
 * of string literals and/or column identifiers.
 *
 * @param x - The value to validate
 * @param columnList - Optional list of valid column names (without '@' prefix) for validation
 * @throws {TypeError} If the value is not a valid CONCAT expression
 * @throws {TypeError} If args is not a non-empty array
 * @throws {TypeError} If any argument is not a string or valid column identifier
 *
 * @example
 * ```ts
 * // Mix column values and literals
 * const expr = {
 *   $$_expression: 'CONCAT',
 *   args: ['@first_name', ' ', '@last_name']
 * };
 * assertConcatExpression(expr, ['first_name', 'last_name']);
 * ```
 */
export const assertConcatExpression: (
  x: unknown,
  columnList?: string[],
) => asserts x is Extract<Expressions, { $$_expression: 'CONCAT' }> = (
  x: unknown,
  columnList?: string[],
): asserts x is Extract<Expressions, { $$_expression: 'CONCAT' }> => {
  assertBaseExpression(x, 'CONCAT');
  if (!('args' in x) || !Array.isArray(x.args) || x.args.length === 0) {
    throw new TypeError(
      `Invalid Expression definition: 'args' must be a non-empty array for CONCAT expression`,
    );
  }
  for (const arg of x.args) {
    // Known column reference accepted; otherwise must be a string
    // literal (@-strings not in columnList fall through as literals).
    if (isColumnIdentifier(arg, columnList)) continue;
    if (typeof arg !== 'string') {
      throw new TypeError(
        `Invalid Expression definition: Invalid argument ${arg} in CONCAT expression`,
      );
    }
  }
};

/**
 * Type guard to check if a value is a valid CONCAT expression.
 *
 * @param x - The value to check
 * @param columnList - Optional list of valid column names (without '@' prefix) for validation
 * @returns `true` if the value is a valid CONCAT expression, `false` otherwise
 *
 * @example
 * ```ts
 * const expr = {
 *   $$_expression: 'CONCAT',
 *   args: ['@first_name', ' ', '@last_name']
 * };
 *
 * if (isConcatExpression(expr, ['first_name', 'last_name'])) {
 *   // expr is narrowed to Extract<Expressions, { $$_expression: 'CONCAT' }>
 *   console.log(`Concatenating ${expr.args.length} parts`);
 * }
 * ```
 */
export const isConcatExpression: (
  x: unknown,
  columnList?: string[],
) => x is Extract<Expressions, { $$_expression: 'CONCAT' }> = (
  x: unknown,
  columnList?: string[],
): x is Extract<Expressions, { $$_expression: 'CONCAT' }> => {
  try {
    assertConcatExpression(x, columnList);
    return true;
  } catch {
    return false;
  }
};

/**
 * Asserts that a value is a valid LOWER expression.
 *
 * The LOWER expression converts a string to lowercase. Accepts a string literal
 * or column identifier.
 *
 * @param x - The value to validate
 * @param columnList - Optional list of valid column names (without '@' prefix) for validation
 * @throws {TypeError} If the value is not a valid LOWER expression
 *
 * @example
 * ```ts
 * const expr = { $$_expression: 'LOWER', args: '@email' };
 * assertLowerExpression(expr, ['email']);
 * ```
 */
export const assertLowerExpression: (
  x: unknown,
  columnList?: string[],
) => asserts x is Extract<Expressions, { $$_expression: 'LOWER' }> = (
  x: unknown,
  columnList?: string[],
): asserts x is Extract<Expressions, { $$_expression: 'LOWER' }> => {
  assertSingleArgStringExpression(x, 'LOWER', columnList);
};

/**
 * Type guard to check if a value is a valid LOWER expression.
 *
 * @param x - The value to check
 * @param columnList - Optional list of valid column names (without '@' prefix) for validation
 * @returns `true` if the value is a valid LOWER expression, `false` otherwise
 *
 * @example
 * ```ts
 * const expr = { $$_expression: 'LOWER', args: '@email' };
 * if (isLowerExpression(expr, ['email'])) {
 *   // expr is narrowed to Extract<Expressions, { $$_expression: 'LOWER' }>
 *   console.log('Will convert to lowercase');
 * }
 * ```
 */
export const isLowerExpression: (
  x: unknown,
  columnList?: string[],
) => x is Extract<Expressions, { $$_expression: 'LOWER' }> = (
  x: unknown,
  columnList?: string[],
): x is Extract<Expressions, { $$_expression: 'LOWER' }> => {
  try {
    assertLowerExpression(x, columnList);
    return true;
  } catch {
    return false;
  }
};

/**
 * Asserts that a value is a valid UPPER expression.
 *
 * The UPPER expression converts a string to uppercase. Accepts a string literal
 * or column identifier.
 *
 * @param x - The value to validate
 * @param columnList - Optional list of valid column names (without '@' prefix) for validation
 * @throws {TypeError} If the value is not a valid UPPER expression
 *
 * @example
 * ```ts
 * const expr = { $$_expression: 'UPPER', args: '@country_code' };
 * assertUpperExpression(expr, ['country_code']);
 * ```
 */
export const assertUpperExpression: (
  x: unknown,
  columnList?: string[],
) => asserts x is Extract<Expressions, { $$_expression: 'UPPER' }> = (
  x: unknown,
  columnList?: string[],
): asserts x is Extract<Expressions, { $$_expression: 'UPPER' }> => {
  assertSingleArgStringExpression(x, 'UPPER', columnList);
};

/**
 * Type guard to check if a value is a valid UPPER expression.
 *
 * @param x - The value to check
 * @param columnList - Optional list of valid column names (without '@' prefix) for validation
 * @returns `true` if the value is a valid UPPER expression, `false` otherwise
 *
 * @example
 * ```ts
 * const expr = { $$_expression: 'UPPER', args: '@country_code' };
 * if (isUpperExpression(expr, ['country_code'])) {
 *   // expr is narrowed to Extract<Expressions, { $$_expression: 'UPPER' }>
 *   console.log('Will convert to uppercase');
 * }
 * ```
 */
export const isUpperExpression: (
  x: unknown,
  columnList?: string[],
) => x is Extract<Expressions, { $$_expression: 'UPPER' }> = (
  x: unknown,
  columnList?: string[],
): x is Extract<Expressions, { $$_expression: 'UPPER' }> => {
  try {
    assertUpperExpression(x, columnList);
    return true;
  } catch {
    return false;
  }
};

/**
 * Asserts that a value is a valid TRIM expression.
 *
 * The TRIM expression removes leading and trailing whitespace from a string.
 * Accepts a string literal or column identifier.
 *
 * @param x - The value to validate
 * @param columnList - Optional list of valid column names (without '@' prefix) for validation
 * @throws {TypeError} If the value is not a valid TRIM expression
 *
 * @example
 * ```ts
 * const expr = { $$_expression: 'TRIM', args: '@user_input' };
 * assertTrimExpression(expr, ['user_input']);
 * ```
 */
export const assertTrimExpression: (
  x: unknown,
  columnList?: string[],
) => asserts x is Extract<Expressions, { $$_expression: 'TRIM' }> = (
  x: unknown,
  columnList?: string[],
): asserts x is Extract<Expressions, { $$_expression: 'TRIM' }> => {
  assertSingleArgStringExpression(x, 'TRIM', columnList);
};

/**
 * Type guard to check if a value is a valid TRIM expression.
 *
 * @param x - The value to check
 * @param columnList - Optional list of valid column names (without '@' prefix) for validation
 * @returns `true` if the value is a valid TRIM expression, `false` otherwise
 *
 * @example
 * ```ts
 * const expr = { $$_expression: 'TRIM', args: '@user_input' };
 * if (isTrimExpression(expr, ['user_input'])) {
 *   // expr is narrowed to Extract<Expressions, { $$_expression: 'TRIM' }>
 *   console.log('Will remove leading and trailing whitespace');
 * }
 * ```
 */
export const isTrimExpression: (
  x: unknown,
  columnList?: string[],
) => x is Extract<Expressions, { $$_expression: 'TRIM' }> = (
  x: unknown,
  columnList?: string[],
): x is Extract<Expressions, { $$_expression: 'TRIM' }> => {
  try {
    assertTrimExpression(x, columnList);
    return true;
  } catch {
    return false;
  }
};

/**
 * Asserts that a value is a valid LTRIM expression.
 *
 * The LTRIM expression removes leading (left-side) whitespace only from a string.
 * Trailing whitespace is preserved. Accepts a string literal or column identifier.
 *
 * @param x - The value to validate
 * @param columnList - Optional list of valid column names (without '@' prefix) for validation
 * @throws {TypeError} If the value is not a valid LTRIM expression
 *
 * @example
 * ```ts
 * const expr = { $$_expression: 'LTRIM', args: '@description' };
 * assertLTrimExpression(expr, ['description']);
 * ```
 */
export const assertLTrimExpression: (
  x: unknown,
  columnList?: string[],
) => asserts x is Extract<Expressions, { $$_expression: 'LTRIM' }> = (
  x: unknown,
  columnList?: string[],
): asserts x is Extract<Expressions, { $$_expression: 'LTRIM' }> => {
  assertSingleArgStringExpression(x, 'LTRIM', columnList);
};

/**
 * Type guard to check if a value is a valid LTRIM expression.
 *
 * @param x - The value to check
 * @param columnList - Optional list of valid column names (without '@' prefix) for validation
 * @returns `true` if the value is a valid LTRIM expression, `false` otherwise
 *
 * @example
 * ```ts
 * const expr = { $$_expression: 'LTRIM', args: '@description' };
 * if (isLTrimExpression(expr, ['description'])) {
 *   // expr is narrowed to Extract<Expressions, { $$_expression: 'LTRIM' }>
 *   console.log('Will remove leading whitespace only');
 * }
 * ```
 */
export const isLTrimExpression: (
  x: unknown,
  columnList?: string[],
) => x is Extract<Expressions, { $$_expression: 'LTRIM' }> = (
  x: unknown,
  columnList?: string[],
): x is Extract<Expressions, { $$_expression: 'LTRIM' }> => {
  try {
    assertLTrimExpression(x, columnList);
    return true;
  } catch {
    return false;
  }
};

/**
 * Asserts that a value is a valid RTRIM expression.
 *
 * The RTRIM expression removes trailing (right-side) whitespace only from a string.
 * Leading whitespace is preserved. Accepts a string literal or column identifier.
 *
 * @param x - The value to validate
 * @param columnList - Optional list of valid column names (without '@' prefix) for validation
 * @throws {TypeError} If the value is not a valid RTRIM expression
 *
 * @example
 * ```ts
 * const expr = { $$_expression: 'RTRIM', args: '@notes' };
 * assertRTrimExpression(expr, ['notes']);
 * ```
 */
export const assertRTrimExpression: (
  x: unknown,
  columnList?: string[],
) => asserts x is Extract<Expressions, { $$_expression: 'RTRIM' }> = (
  x: unknown,
  columnList?: string[],
): asserts x is Extract<Expressions, { $$_expression: 'RTRIM' }> => {
  assertSingleArgStringExpression(x, 'RTRIM', columnList);
};

/**
 * Type guard to check if a value is a valid RTRIM expression.
 *
 * @param x - The value to check
 * @param columnList - Optional list of valid column names (without '@' prefix) for validation
 * @returns `true` if the value is a valid RTRIM expression, `false` otherwise
 *
 * @example
 * ```ts
 * const expr = { $$_expression: 'RTRIM', args: '@notes' };
 * if (isRTrimExpression(expr, ['notes'])) {
 *   // expr is narrowed to Extract<Expressions, { $$_expression: 'RTRIM' }>
 *   console.log('Will remove trailing whitespace only');
 * }
 * ```
 */
export const isRTrimExpression: (
  x: unknown,
  columnList?: string[],
) => x is Extract<Expressions, { $$_expression: 'RTRIM' }> = (
  x: unknown,
  columnList?: string[],
): x is Extract<Expressions, { $$_expression: 'RTRIM' }> => {
  try {
    assertRTrimExpression(x, columnList);
    return true;
  } catch {
    return false;
  }
};

/**
 * Asserts that a value is a valid SUBSTR expression.
 *
 * The SUBSTR expression extracts a portion of a string starting at a specified
 * position. The start position is 1-based (SQL-native). The length parameter is
 * optional; if omitted, extracts to the end of the string.
 *
 * @param x - The value to validate
 * @param columnList - Optional list of valid column names (without '@' prefix) for validation
 * @throws {TypeError} If the value is not a valid SUBSTR expression
 * @throws {TypeError} If required properties are missing
 * @throws {TypeError} If arguments are not valid strings, numbers, or column identifiers
 *
 * @example
 * ```ts
 * // Omit `length` to extract to the end of the string.
 * const expr = {
 *   $$_expression: 'SUBSTR',
 *   args: { string: '@description', start: 1, length: 100 }
 * };
 * assertSubstrExpression(expr, ['description']);
 * ```
 */
export const assertSubstrExpression: (
  x: unknown,
  columnList?: string[],
) => asserts x is Extract<Expressions, { $$_expression: 'SUBSTR' }> = (
  x: unknown,
  columnList?: string[],
): asserts x is Extract<Expressions, { $$_expression: 'SUBSTR' }> => {
  assertBaseExpression(x, 'SUBSTR');
  if (!('args' in x)) {
    throw new TypeError(
      `Invalid Expression definition: Missing 'args' property for SUBSTR expression`,
    );
  }
  if (typeof x.args !== 'object' || x.args === null) {
    throw new TypeError(
      `Invalid Expression definition: 'args' must be an object for SUBSTR expression`,
    );
  }
  if (!('string' in x.args)) {
    throw new TypeError(
      `Invalid Expression definition: Missing 'string' property in args for SUBSTR expression`,
    );
  }
  validateStringArg(x.args.string, 'string', 'SUBSTR', columnList);

  if (!('start' in x.args)) {
    throw new TypeError(
      `Invalid Expression definition: Missing 'start' property in args for SUBSTR expression`,
    );
  }
  validateNumberArg(x.args.start, 'start', 'SUBSTR', columnList);

  if ('length' in x.args && x.args.length !== undefined) {
    validateNumberArg(x.args.length, 'length', 'SUBSTR', columnList);
  }
};

/**
 * Type guard to check if a value is a valid SUBSTR expression.
 *
 * @param x - The value to check
 * @param columnList - Optional list of valid column names (without '@' prefix) for validation
 * @returns `true` if the value is a valid SUBSTR expression, `false` otherwise
 *
 * @example
 * ```ts
 * const expr = {
 *   $$_expression: 'SUBSTR',
 *   args: { string: '@description', start: 0, length: 100 }
 * };
 *
 * if (isSubstrExpression(expr, ['description'])) {
 *   // expr is narrowed to Extract<Expressions, { $$_expression: 'SUBSTR' }>
 *   const { string, start, length } = expr.args;
 *   console.log(`Extracting from ${string} at position ${start}`);
 * }
 * ```
 */
export const isSubstrExpression: (
  x: unknown,
  columnList?: string[],
) => x is Extract<Expressions, { $$_expression: 'SUBSTR' }> = (
  x: unknown,
  columnList?: string[],
): x is Extract<Expressions, { $$_expression: 'SUBSTR' }> => {
  try {
    assertSubstrExpression(x, columnList);
    return true;
  } catch {
    return false;
  }
};

/**
 * Asserts that a value is a valid REPLACE expression.
 *
 * The REPLACE expression finds all occurrences of a search string and replaces
 * them with a replacement string. All three arguments (string, search, replace)
 * can be literals or column identifiers.
 *
 * @param x - The value to validate
 * @param columnList - Optional list of valid column names (without '@' prefix) for validation
 * @throws {TypeError} If the value is not a valid REPLACE expression
 * @throws {TypeError} If required properties are missing
 * @throws {TypeError} If arguments are not valid strings or column identifiers
 *
 * @example
 * ```ts
 * const expr = {
 *   $$_expression: 'REPLACE',
 *   args: { string: '@description', search: 'old_term', replace: 'new_term' }
 * };
 * assertReplaceExpression(expr, ['description']);
 * ```
 */
export const assertReplaceExpression: (
  x: unknown,
  columnList?: string[],
) => asserts x is Extract<Expressions, { $$_expression: 'REPLACE' }> = (
  x: unknown,
  columnList?: string[],
): asserts x is Extract<Expressions, { $$_expression: 'REPLACE' }> => {
  assertBaseExpression(x, 'REPLACE');
  if (!('args' in x)) {
    throw new TypeError(
      `Invalid Expression definition: Missing 'args' property for REPLACE expression`,
    );
  }
  if (typeof x.args !== 'object' || x.args === null) {
    throw new TypeError(
      `Invalid Expression definition: 'args' must be an object for REPLACE expression`,
    );
  }
  if (!('string' in x.args)) {
    throw new TypeError(
      `Invalid Expression definition: Missing 'string' property in args for REPLACE expression`,
    );
  }
  validateStringArg(x.args.string, 'string', 'REPLACE', columnList);

  if (!('search' in x.args)) {
    throw new TypeError(
      `Invalid Expression definition: Missing 'search' property in args for REPLACE expression`,
    );
  }
  validateStringArg(x.args.search, 'search', 'REPLACE', columnList);

  if (!('replace' in x.args)) {
    throw new TypeError(
      `Invalid Expression definition: Missing 'replace' property in args for REPLACE expression`,
    );
  }
  validateStringArg(x.args.replace, 'replace', 'REPLACE', columnList);
};

/**
 * Type guard to check if a value is a valid REPLACE expression.
 *
 * @param x - The value to check
 * @param columnList - Optional list of valid column names (without '@' prefix) for validation
 * @returns `true` if the value is a valid REPLACE expression, `false` otherwise
 *
 * @example
 * ```ts
 * const expr = {
 *   $$_expression: 'REPLACE',
 *   args: { string: '@text', search: 'old', replace: 'new' }
 * };
 *
 * if (isReplaceExpression(expr, ['text'])) {
 *   // expr is narrowed to Extract<Expressions, { $$_expression: 'REPLACE' }>
 *   console.log('Will replace all occurrences');
 * }
 * ```
 */
export const isReplaceExpression: (
  x: unknown,
  columnList?: string[],
) => x is Extract<Expressions, { $$_expression: 'REPLACE' }> = (
  x: unknown,
  columnList?: string[],
): x is Extract<Expressions, { $$_expression: 'REPLACE' }> => {
  try {
    assertReplaceExpression(x, columnList);
    return true;
  } catch {
    return false;
  }
};

/**
 * Asserts that a value is a valid LPAD expression.
 *
 * The LPAD expression pads a string on the left side to reach a specified length.
 * The fill character defaults to space if not provided. If the string is already
 * longer than the specified length, it remains unchanged.
 *
 * @param x - The value to validate
 * @param columnList - Optional list of valid column names (without '@' prefix) for validation
 * @throws {TypeError} If the value is not a valid LPAD expression
 * @throws {TypeError} If required properties are missing
 * @throws {TypeError} If arguments are not valid strings, numbers, or column identifiers
 *
 * @example
 * ```ts
 * // `fill` defaults to a space when omitted.
 * const expr = {
 *   $$_expression: 'LPAD',
 *   args: { string: '@id', length: 8, fill: '0' }
 * };
 * assertLPadExpression(expr, ['id']);
 * ```
 */
export const assertLPadExpression: (
  x: unknown,
  columnList?: string[],
) => asserts x is Extract<Expressions, { $$_expression: 'LPAD' }> = (
  x: unknown,
  columnList?: string[],
): asserts x is Extract<Expressions, { $$_expression: 'LPAD' }> => {
  assertBaseExpression(x, 'LPAD');
  if (!('args' in x)) {
    throw new TypeError(
      `Invalid Expression definition: Missing 'args' property for LPAD expression`,
    );
  }
  if (typeof x.args !== 'object' || x.args === null) {
    throw new TypeError(
      `Invalid Expression definition: 'args' must be an object for LPAD expression`,
    );
  }
  if (!('string' in x.args)) {
    throw new TypeError(
      `Invalid Expression definition: Missing 'string' property in args for LPAD expression`,
    );
  }
  validateStringArg(x.args.string, 'string', 'LPAD', columnList);

  if (!('length' in x.args)) {
    throw new TypeError(
      `Invalid Expression definition: Missing 'length' property in args for LPAD expression`,
    );
  }
  validateNumberArg(x.args.length, 'length', 'LPAD', columnList);

  if ('fill' in x.args && x.args.fill !== undefined) {
    validateStringArg(x.args.fill, 'fill', 'LPAD', columnList);
  }
};

/**
 * Type guard to check if a value is a valid LPAD expression.
 *
 * @param x - The value to check
 * @param columnList - Optional list of valid column names (without '@' prefix) for validation
 * @returns `true` if the value is a valid LPAD expression, `false` otherwise
 *
 * @example
 * ```ts
 * const expr = {
 *   $$_expression: 'LPAD',
 *   args: { string: '@id', length: 8, fill: '0' }
 * };
 *
 * if (isLPadExpression(expr, ['id'])) {
 *   // expr is narrowed to Extract<Expressions, { $$_expression: 'LPAD' }>
 *   console.log('Will pad on the left side');
 * }
 * ```
 */
export const isLPadExpression: (
  x: unknown,
  columnList?: string[],
) => x is Extract<Expressions, { $$_expression: 'LPAD' }> = (
  x: unknown,
  columnList?: string[],
): x is Extract<Expressions, { $$_expression: 'LPAD' }> => {
  try {
    assertLPadExpression(x, columnList);
    return true;
  } catch {
    return false;
  }
};

/**
 * Asserts that a value is a valid RPAD expression.
 *
 * The RPAD expression pads a string on the right side to reach a specified length.
 * The fill character defaults to space if not provided. If the string is already
 * longer than the specified length, it remains unchanged.
 *
 * @param x - The value to validate
 * @param columnList - Optional list of valid column names (without '@' prefix) for validation
 * @throws {TypeError} If the value is not a valid RPAD expression
 * @throws {TypeError} If required properties are missing
 * @throws {TypeError} If arguments are not valid strings, numbers, or column identifiers
 *
 * @example
 * ```ts
 * // `fill` defaults to a space when omitted.
 * const expr = {
 *   $$_expression: 'RPAD',
 *   args: { string: '@product_name', length: 30, fill: '.' }
 * };
 * assertRPadExpression(expr, ['product_name']);
 * ```
 */
export const assertRPadExpression: (
  x: unknown,
  columnList?: string[],
) => asserts x is Extract<Expressions, { $$_expression: 'RPAD' }> = (
  x: unknown,
  columnList?: string[],
): asserts x is Extract<Expressions, { $$_expression: 'RPAD' }> => {
  assertBaseExpression(x, 'RPAD');
  if (!('args' in x)) {
    throw new TypeError(
      `Invalid Expression definition: Missing 'args' property for RPAD expression`,
    );
  }
  if (typeof x.args !== 'object' || x.args === null) {
    throw new TypeError(
      `Invalid Expression definition: 'args' must be an object for RPAD expression`,
    );
  }
  if (!('string' in x.args)) {
    throw new TypeError(
      `Invalid Expression definition: Missing 'string' property in args for RPAD expression`,
    );
  }
  validateStringArg(x.args.string, 'string', 'RPAD', columnList);

  if (!('length' in x.args)) {
    throw new TypeError(
      `Invalid Expression definition: Missing 'length' property in args for RPAD expression`,
    );
  }
  validateNumberArg(x.args.length, 'length', 'RPAD', columnList);

  if ('fill' in x.args && x.args.fill !== undefined) {
    validateStringArg(x.args.fill, 'fill', 'RPAD', columnList);
  }
};

/**
 * Type guard to check if a value is a valid RPAD expression.
 *
 * @param x - The value to check
 * @param columnList - Optional list of valid column names (without '@' prefix) for validation
 * @returns `true` if the value is a valid RPAD expression, `false` otherwise
 *
 * @example
 * ```ts
 * const expr = {
 *   $$_expression: 'RPAD',
 *   args: { string: '@product_name', length: 30, fill: ' ' }
 * };
 *
 * if (isRPadExpression(expr, ['product_name'])) {
 *   // expr is narrowed to Extract<Expressions, { $$_expression: 'RPAD' }>
 *   console.log('Will pad on the right side');
 * }
 * ```
 */
export const isRPadExpression: (
  x: unknown,
  columnList?: string[],
) => x is Extract<Expressions, { $$_expression: 'RPAD' }> = (
  x: unknown,
  columnList?: string[],
): x is Extract<Expressions, { $$_expression: 'RPAD' }> => {
  try {
    assertRPadExpression(x, columnList);
    return true;
  } catch {
    return false;
  }
};

/**
 * Asserts that a value is a valid ENCRYPT expression.
 *
 * The ENCRYPT expression performs symmetric encryption on data using a secret key.
 * Database support varies:
 * - PostgreSQL: Requires pgcrypto extension, uses AES encryption
 * - MariaDB: Native AES_ENCRYPT function
 * - SQLite: No built-in support, stores as-is without encryption
 * - MongoDB: No built-in support, stores as-is without encryption
 *
 * Note: For SQLite and MongoDB, implement application-level encryption before
 * passing data to DAM if encryption is required.
 *
 * @param x - The value to validate
 * @param columnList - Optional list of valid column names (without '@' prefix) for validation
 * @throws {TypeError} If the value is not a valid ENCRYPT expression
 * @throws {TypeError} If required properties are missing
 * @throws {TypeError} If secret or data arguments are invalid
 *
 * @example
 * ```ts
 * const expr = {
 *   $$_expression: 'ENCRYPT',
 *   args: { secret: 'encryption-key', data: '@ssn' }
 * };
 * assertEncryptExpression(expr, ['ssn']);
 * ```
 */
export const assertEncryptExpression: (
  x: unknown,
  columnList?: string[],
) => asserts x is Extract<Expressions, { $$_expression: 'ENCRYPT' }> = (
  x: unknown,
  columnList?: string[],
): asserts x is Extract<Expressions, { $$_expression: 'ENCRYPT' }> => {
  assertBaseExpression(x, 'ENCRYPT');
  if (!('args' in x)) {
    throw new TypeError(
      `Invalid Expression definition: Missing 'args' property for ENCRYPT expression`,
    );
  }
  if (typeof x.args !== 'object' || x.args === null) {
    throw new TypeError(
      `Invalid Expression definition: 'args' must be an object for ENCRYPT expression`,
    );
  }
  if (!('secret' in x.args)) {
    throw new TypeError(
      `Invalid Expression definition: Missing 'secret' property in args for ENCRYPT expression`,
    );
  }
  // secret: column ref or string literal (including @-strings not in list).
  if (!isColumnIdentifier(x.args.secret, columnList)) {
    if (typeof x.args.secret !== 'string') {
      throw new TypeError(
        `Invalid Expression definition: secret must be a string or column identifier in ENCRYPT expression`,
      );
    }
  }

  if (!('data' in x.args)) {
    throw new TypeError(
      `Invalid Expression definition: Missing 'data' property in args for ENCRYPT expression`,
    );
  }
  // data: column ref or any literal. @-strings not in list silently
  // become literal strings — that's the desired semantic.
  // (No further validation needed; isColumnIdentifier handles col-ref check.)
};

/**
 * Type guard to check if a value is a valid ENCRYPT expression.
 *
 * @param x - The value to check
 * @param columnList - Optional list of valid column names (without '@' prefix) for validation
 * @returns `true` if the value is a valid ENCRYPT expression, `false` otherwise
 *
 * @example
 * ```ts
 * const expr = {
 *   $$_expression: 'ENCRYPT',
 *   args: { secret: 'key', data: '@ssn' }
 * };
 *
 * if (isEncryptExpression(expr, ['ssn'])) {
 *   // expr is narrowed to Extract<Expressions, { $$_expression: 'ENCRYPT' }>
 *   console.log('Will encrypt data using symmetric encryption');
 * }
 * ```
 */
export const isEncryptExpression: (
  x: unknown,
  columnList?: string[],
) => x is Extract<Expressions, { $$_expression: 'ENCRYPT' }> = (
  x: unknown,
  columnList?: string[],
): x is Extract<Expressions, { $$_expression: 'ENCRYPT' }> => {
  try {
    assertEncryptExpression(x, columnList);
    return true;
  } catch {
    return false;
  }
};

/**
 * Asserts that a value is a valid DECRYPT expression.
 *
 * The DECRYPT expression performs symmetric decryption on encrypted data using
 * a secret key. Database support varies:
 * - PostgreSQL: Requires pgcrypto extension, uses AES decryption
 * - MariaDB: Native AES_DECRYPT function
 * - SQLite: No built-in support, returns value as-is
 * - MongoDB: No built-in support, returns value as-is
 *
 * Note: Only works on data encrypted by the corresponding database. Must use
 * the same secret key that was used for encryption.
 *
 * @param x - The value to validate
 * @param columnList - Optional list of valid column names (without '@' prefix) for validation
 * @throws {TypeError} If the value is not a valid DECRYPT expression
 * @throws {TypeError} If required properties are missing
 * @throws {TypeError} If secret or data arguments are invalid
 *
 * @example
 * ```ts
 * const expr = {
 *   $$_expression: 'DECRYPT',
 *   args: { secret: 'encryption-key', data: '@encrypted_ssn' }
 * };
 * assertDecryptExpression(expr, ['encrypted_ssn']);
 * ```
 */
export const assertDecryptExpression: (
  x: unknown,
  columnList?: string[],
) => asserts x is Extract<Expressions, { $$_expression: 'DECRYPT' }> = (
  x: unknown,
  columnList?: string[],
): asserts x is Extract<Expressions, { $$_expression: 'DECRYPT' }> => {
  assertBaseExpression(x, 'DECRYPT');
  if (!('args' in x)) {
    throw new TypeError(
      `Invalid Expression definition: Missing 'args' property for DECRYPT expression`,
    );
  }
  if (typeof x.args !== 'object' || x.args === null) {
    throw new TypeError(
      `Invalid Expression definition: 'args' must be an object for DECRYPT expression`,
    );
  }
  if (!('secret' in x.args)) {
    throw new TypeError(
      `Invalid Expression definition: Missing 'secret' property in args for DECRYPT expression`,
    );
  }
  // secret: column ref or string literal (including @-strings not in list).
  if (!isColumnIdentifier(x.args.secret, columnList)) {
    if (typeof x.args.secret !== 'string') {
      throw new TypeError(
        `Invalid Expression definition: secret must be a string or column identifier in DECRYPT expression`,
      );
    }
  }

  if (!('data' in x.args)) {
    throw new TypeError(
      `Invalid Expression definition: Missing 'data' property in args for DECRYPT expression`,
    );
  }
  // data: column ref or any literal. @-strings not in list silently
  // become literal strings — that's the desired semantic.
};

/**
 * Type guard to check if a value is a valid DECRYPT expression.
 *
 * @param x - The value to check
 * @param columnList - Optional list of valid column names (without '@' prefix) for validation
 * @returns `true` if the value is a valid DECRYPT expression, `false` otherwise
 *
 * @example
 * ```ts
 * const expr = {
 *   $$_expression: 'DECRYPT',
 *   args: { secret: 'key', data: '@encrypted_ssn' }
 * };
 *
 * if (isDecryptExpression(expr, ['encrypted_ssn'])) {
 *   // expr is narrowed to Extract<Expressions, { $$_expression: 'DECRYPT' }>
 *   console.log('Will decrypt data using symmetric decryption');
 * }
 * ```
 */
export const isDecryptExpression: (
  x: unknown,
  columnList?: string[],
) => x is Extract<Expressions, { $$_expression: 'DECRYPT' }> = (
  x: unknown,
  columnList?: string[],
): x is Extract<Expressions, { $$_expression: 'DECRYPT' }> => {
  try {
    assertDecryptExpression(x, columnList);
    return true;
  } catch {
    return false;
  }
};

/**
 * Asserts that a value is a valid HASH expression.
 *
 * HASH creates a cryptographic hash of the provided data.
 * Database support varies - PostgreSQL supports digest() function,
 * MariaDB supports SHA2(), while SQLite and MongoDB have limited support.
 *
 * @param x - The value to validate
 * @param columnList - Optional list of valid column names (without '@' prefix) for validation
 * @throws {TypeError} If the expression structure is invalid
 * @throws {TypeError} If required properties are missing
 * @throws {TypeError} If the args property is not valid
 *
 * @example
 * ```ts
 * const expr = { $$_expression: 'HASH', args: '@password' };
 * assertHashExpression(expr, ['password']);
 * ```
 */
export const assertHashExpression: (
  x: unknown,
  columnList?: string[],
) => asserts x is Extract<Expressions, { $$_expression: 'HASH' }> = (
  x: unknown,
  columnList?: string[],
): asserts x is Extract<Expressions, { $$_expression: 'HASH' }> => {
  assertBaseExpression(x, 'HASH');
  if (!('args' in x)) {
    throw new TypeError(
      `Invalid Expression definition: Missing 'args' property for HASH expression`,
    );
  }
  // args can be column ref or any literal (string/number/bigint/Date/boolean).
  // @-strings not in the list fall through and are treated as string literals.
  if (isColumnIdentifier(x.args, columnList)) return;
  if (
    typeof x.args !== 'string' &&
    typeof x.args !== 'number' &&
    typeof x.args !== 'bigint' &&
    typeof x.args !== 'boolean' &&
    !(x.args instanceof Date)
  ) {
    throw new TypeError(
      `Invalid Expression definition: args must be a string, number, bigint, Date, boolean, or column identifier in HASH expression, got ${typeof x
        .args}`,
    );
  }
};

/**
 * Type guard to check if a value is a valid HASH expression.
 *
 * @param x - The value to check
 * @param columnList - Optional list of valid column names (without '@' prefix) for validation
 * @returns `true` if the value is a valid HASH expression, `false` otherwise
 *
 * @example
 * ```ts
 * const expr = {
 *   $$_expression: 'HASH',
 *   args: '@email'
 * };
 *
 * if (isHashExpression(expr, ['email'])) {
 *   // expr is narrowed to Extract<Expressions, { $$_expression: 'HASH' }>
 *   console.log('Will hash the email value');
 * }
 * ```
 */
export const isHashExpression: (
  x: unknown,
  columnList?: string[],
) => x is Extract<Expressions, { $$_expression: 'HASH' }> = (
  x: unknown,
  columnList?: string[],
): x is Extract<Expressions, { $$_expression: 'HASH' }> => {
  try {
    assertHashExpression(x, columnList);
    return true;
  } catch {
    return false;
  }
};

/**
 * Asserts that a value is a valid string-related expression.
 *
 * This is a comprehensive validator that checks if a value matches any of the
 * supported string expression types. It automatically delegates to the appropriate
 * specific validator based on the expression type.
 *
 * Supported string expression types:
 * - UUID: Generate UUID v4
 * - CONCAT: Concatenate multiple strings
 * - LOWER: Convert to lowercase
 * - UPPER: Convert to uppercase
 * - TRIM: Remove leading and trailing whitespace
 * - LTRIM: Remove leading whitespace only
 * - RTRIM: Remove trailing whitespace only
 * - SUBSTR: Extract substring
 * - REPLACE: Replace string occurrences
 * - LPAD: Left pad string
 * - RPAD: Right pad string
 * - ENCRYPT: Symmetric encryption
 * - DECRYPT: Symmetric decryption
 * - HASH: Cryptographic hashing
 *
 * @param x - The value to validate
 * @param columnList - Optional list of valid column names (without '@' prefix) for validation
 * @throws {TypeError} If the value is not a valid string expression
 * @throws {TypeError} If the expression type is not a recognized string type
 *
 * @example
 * ```ts
 * // Delegates to the matching per-type validator...
 * assertStringExpression({ $$_expression: 'LOWER', args: '@email' }, ['email']);
 * // ...and rejects a non-string expression type.
 * assertStringExpression({ $$_expression: 'SUM' });  // throws: TypeError
 * ```
 */
export const assertStringExpression: (
  x: unknown,
  columnList?: string[],
  depth?: number,
  maxDepth?: number,
) => asserts x is Extract<Expressions, { $$_expression: StringExpressions }> = (
  x: unknown,
  columnList?: string[],
  depth = 0,
  maxDepth = 10,
): asserts x is Extract<Expressions, { $$_expression: StringExpressions }> => {
  if (depth > maxDepth) {
    throw new TypeError(
      `Expression exceeds maximum nesting depth of ${maxDepth}. ` +
        `This may indicate overly complex expression or circular reference.`,
    );
  }
  assertBaseExpression(x);
  if (x.$$_expression === 'UUID') {
    assertUUIDExpression(x);
  } else if (x.$$_expression === 'CONCAT') {
    assertConcatExpression(x, columnList);
  } else if (x.$$_expression === 'LOWER') {
    assertLowerExpression(x, columnList);
  } else if (x.$$_expression === 'UPPER') {
    assertUpperExpression(x, columnList);
  } else if (x.$$_expression === 'TRIM') {
    assertTrimExpression(x, columnList);
  } else if (x.$$_expression === 'LTRIM') {
    assertLTrimExpression(x, columnList);
  } else if (x.$$_expression === 'RTRIM') {
    assertRTrimExpression(x, columnList);
  } else if (x.$$_expression === 'SUBSTR') {
    assertSubstrExpression(x, columnList);
  } else if (x.$$_expression === 'REPLACE') {
    assertReplaceExpression(x, columnList);
  } else if (x.$$_expression === 'LPAD') {
    assertLPadExpression(x, columnList);
  } else if (x.$$_expression === 'RPAD') {
    assertRPadExpression(x, columnList);
  } else if (x.$$_expression === 'ENCRYPT') {
    assertEncryptExpression(x, columnList);
  } else if (x.$$_expression === 'DECRYPT') {
    assertDecryptExpression(x, columnList);
  } else if (x.$$_expression === 'HASH') {
    assertHashExpression(x, columnList);
  } else {
    throw new TypeError(
      `Invalid Expression type: Expected a String expression type, got '${x.$$_expression}'`,
    );
  }
};

/**
 * Type guard to check if a value is a valid string-related expression.
 *
 * This is a comprehensive type guard that checks if a value matches any of the
 * supported string expression types. It narrows the type to a union of all string expressions.
 *
 * @param x - The value to check
 * @param columnList - Optional list of valid column names (without '@' prefix) for validation
 * @returns `true` if the value is a valid string expression, `false` otherwise
 *
 * @example
 * ```ts
 * declare function getExpression(): unknown;
 * declare function getAllExpressions(): unknown[];
 * declare function buildQuery(): unknown;
 * declare function executeQuery(x: unknown): void;
 *
 * const expr: unknown = getExpression();
 *
 * if (isStringExpression(expr)) {
 *   // expr is narrowed to Extract<Expressions, { $$_expression: StringExpressions }>
 *   switch (expr.$$_expression) {
 *     case 'UUID':
 *       console.log('UUID generation');
 *       break;
 *     case 'CONCAT':
 *       console.log('Concatenating:', expr.args);
 *       break;
 *     case 'LOWER':
 *     case 'UPPER':
 *       console.log('Case conversion');
 *       break;
 *     case 'TRIM':
 *     case 'LTRIM':
 *     case 'RTRIM':
 *       console.log('Whitespace trimming');
 *       break;
 *     case 'SUBSTR':
 *       console.log('Substring extraction');
 *       break;
 *     case 'REPLACE':
 *       console.log('String replacement');
 *       break;
 *     case 'LPAD':
 *     case 'RPAD':
 *       console.log('String padding');
 *       break;
 *     case 'ENCRYPT':
 *     case 'DECRYPT':
 *       console.log('Encryption/Decryption');
 *       break;
 *     case 'HASH':
 *       console.log('Cryptographic hashing');
 *       break;
 *   }
 * }
 *
 * // Filter expressions by category
 * const expressions: unknown[] = getAllExpressions();
 * const stringExpressions = expressions.filter((x) =>
 *   isStringExpression(x)
 * );
 * console.log(`Found ${stringExpressions.length} string expressions`);
 *
 * // Validate query expressions with column validation
 * const queryExpr: unknown = buildQuery();
 * if (isStringExpression(queryExpr, ['name', 'email', 'description'])) {
 *   // All string references are validated against column list
 *   executeQuery(queryExpr);
 * }
 * ```
 */
export const isStringExpression: (
  x: unknown,
  columnList?: string[],
  depth?: number,
  maxDepth?: number,
) => x is Extract<Expressions, { $$_expression: StringExpressions }> = (
  x: unknown,
  columnList?: string[],
  depth = 0,
  maxDepth = 10,
): x is Extract<Expressions, { $$_expression: StringExpressions }> => {
  try {
    assertStringExpression(x, columnList, depth, maxDepth);
    return true;
  } catch {
    return false;
  }
};
