import { TranslatorConfig } from '../../types/mod.ts';

export const MariaTranslatorConfig: TranslatorConfig = {
  quote: {
    column: '`',
    value: '\'',
  },
  dataTypes: {
    'INT': 'INTEGER',
    'INTEGER': 'INTEGER',
    'SMALLINT': 'INTEGER',
    'TINYINT': 'INTEGER',
    'SERIAL': 'AUTO_INCREMENT',
    'SMALLSERIAL': 'AUTO_INCREMENT',
    'BIGSERIAL': 'AUTO_INCREMENT',
    'BIGINT': 'BIGINT',
    'BIT': 'BOOLEAN',
    'BOOLEAN': 'BOOLEAN',
    'BINARY': 'BOOLEAN',
    'REAL': 'REAL',
    'FLOAT': 'DOUBLE',
    'DOUBLE PRECISION': 'DOUBLE',
    'DOUBLE': 'DOUBLE',
    'NUMERIC': 'NUMERIC',
    'NUMBER': 'NUMERIC',
    'DECIMAL': 'DECIMAL',
    'MONEY': 'DECIMAL',
    'CHAR': 'CHARACTER',
    'CHARACTER': 'CHARACTER',
    'VARCHAR': 'VARCHAR',
    'NVARCHAR': 'VARCHAR',
    'NCHAR': 'CHARACTER',
    'CHARACTER VARYING': 'VARCHAR',
    'DATE': 'DATE',
    'TIME': 'TIME',
    'DATETIME': 'DATETIME',
    'TIMESTAMP': 'TIMESTAMP',
    'BYTEA': 'TEXT',
    'TEXT': 'TEXT',
    'UUID': 'UUID',
    'JSON': 'JSON',
    'ARRAY': 'TEXT',
    'ARRAY_STRING': 'TEXT',
    'ARRAY_INTEGER': 'TEXT',
    'ARRAY_BIGINT': 'TEXT',
    'ARRAY_DECIMAL': 'TEXT',
    'ARRAY_BOOLEAN': 'TEXT',
    'ARRAY_DATE': 'TEXT',
    'AUTO_INCREMENT': 'AUTO_INCREMENT',
  },
  generators: {
    'CURRENT_DATE': '${CURRENT_DATE}',
    'CURRENT_TIME': '${CURRENT_TIME}',
    'CURRENT_DATETIME': '${CURRENT_DATETIME}',
    'CURRENT_TIMESTAMP': '${CURRENT_TIMESTAMP}',
    'CURRENT_MONTH': '${LAST_DAY}',
    'NOW': '${NOW()}',
    'UUID': '${uuid()}',
    'SYS_GUID': '${SYS_GUID()}',
  },
};
