ignore:
  - '**/tests/**/*.ts'
  - '**/**.bench.ts'
  - '**/**.test.ts'
  - '**/fixtures/**/**'
  - .github/**
coverage:
  precision: 2
  round: down
  range: 70...90
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 70%
        threshold: 5%
    changes: true
comment:
  layout: 'reach, diff, flags, files, footer'
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  after_n_builds: 1
github_checks:
  annotations: true
component_management:
  individual_components:
    - component_id: cacher
      name: Cacher
      paths:
        - cacher/**/*.ts
    - component_id: crypt
      name: Crypt
      paths:
        - crypt/**/*.ts
    - component_id: dam
      name: Dam
      paths:
        - dam/**/*.ts
    - component_id: guardian
      name: Guardian
      paths:
        - guardian/**/*.ts
    - component_id: id
      name: Id
      paths:
        - id/**/*.ts
    - component_id: norm
      name: Norm
      paths:
        - norm/**/*.ts
    - component_id: restler
      name: Restler
      paths:
        - restler/**/*.ts
    - component_id: slogger
      name: Slogger
      paths:
        - slogger/**/*.ts
    - component_id: utils
      name: Utils
      paths:
        - utils/**/*.ts
