import type { FlattenEntity } from '@tundralibs/utils';
import type { GetColumnByType } from '../common/GetColumnByType.ts';
import type { TableType } from '../common/TableType.ts';
import type { NumericExpressions } from './NumericExpressions.ts';
import type { TimeUnit } from './TimeUnit.ts';

/**
 * A single argument to an arithmetic expression: a numeric column
 * reference, a numeric literal, or a nested expression that itself
 * yields a number.
 *
 * Nesting is what `SUBTRACT(total, MULTIPLY(price, qty))` needs.
 * The runtime has always supported it —
 * `AbstractTranslator._translateExpression` recurses through
 * `__renderExprArg`, and `assertNumericExpression` validates nested
 * args to a depth of 10 — so the nested member only brings the type
 * in line with the behaviour on both sides of it.
 *
 * Restricted to {@link NumericExpressions} rather than the whole
 * {@link Expressions} union: that is exactly the set the runtime
 * validator accepts in a numeric position, so a string expression
 * such as `CONCAT` stays rejected at compile time instead of
 * throwing at assert time.
 *
 * @template T  - Table schema type.
 * @template FT - Flattened table type with `'@'` prefix for column
 *                references.
 *
 * @internal
 */
type NumericExpressionArg<
  T extends TableType,
  FT extends FlattenEntity<T, '', '@'>,
> =
  | GetColumnByType<FT, number | bigint>
  | number
  | bigint
  | Extract<Expressions<T, FT>, { $$_expression: NumericExpressions }>;

/**
 * Type-safe expression definitions for computed values in database
 * queries.
 *
 * Expressions allow calculations, transformations, and operations
 * on data within queries. They can be used in:
 * - `SELECT` projections (calculated columns).
 * - `WHERE` clauses (computed conditions).
 * - `ORDER BY` (sort by computed values).
 * - `UPDATE SET` (computed updates).
 *
 * @template T  - Table schema type.
 * @template FT - Flattened table type with `'@'` prefix for column
 *                references.
 *
 * ## Categories
 *
 * **Numeric** (returns number/bigint): `ADD`, `SUBTRACT`,
 * `MULTIPLY`, `DIVIDE`, `MODULO`, `ABS`, `CEIL`, `FLOOR`, `ROUND`,
 * `POWER`, `SQRT`, `LENGTH`, `DATE_DIFF`.
 *
 * **String** (returns string): `CONCAT`, `LOWER`, `UPPER`, `TRIM`,
 * `LTRIM`, `RTRIM`, `SUBSTR`, `REPLACE`, `LPAD`, `RPAD`.
 *
 * **Date** (returns Date): `NOW`, `CURRENT_DATE`, `CURRENT_TIME`,
 * `CURRENT_TIMESTAMP`, `CURRENT_TIMESTAMPTZ`, `DATE_ADD`.
 *
 * **Cryptographic (platform-dependent)**: `ENCRYPT`, `DECRYPT`,
 * `HASH`.
 *
 * **Utility**: `UUID`. (`COALESCE`, `NULLIF`, `CAST` are TODOs;
 * tracked as commented-out branches below.)
 *
 * ## Database compatibility
 *
 * Most expressions are supported across PostgreSQL, MariaDB,
 * SQLite, and MongoDB. The translators emit the appropriate syntax
 * for each engine. Platform-specific notes:
 * - `ENCRYPT` / `DECRYPT` / `HASH`: limited support on SQLite and
 *   MongoDB (stores as-is).
 * - `UUID`: generated by DAM for SQLite and MongoDB (not
 *   database-generated).
 * - `CURRENT_TIMESTAMPTZ`: PostgreSQL-specific; translates to
 *   `CURRENT_TIMESTAMP` on others.
 */
export type Expressions<
  T extends TableType = TableType,
  FT extends FlattenEntity<T, '', '@'> = FlattenEntity<T, '', '@'>,
> = {
  /** Addition: sum of all numeric arguments. */
  $$_expression: 'ADD';
  args: Array<NumericExpressionArg<T, FT>>;
} | {
  /** Subtraction: subtract remaining args from the first. */
  $$_expression: 'SUBTRACT';
  args: Array<NumericExpressionArg<T, FT>>;
} | {
  /** Multiplication: product of all numeric arguments. */
  $$_expression: 'MULTIPLY';
  args: Array<NumericExpressionArg<T, FT>>;
} | {
  /** Division: divide first arg by second. */
  $$_expression: 'DIVIDE';
  args: Array<NumericExpressionArg<T, FT>>;
} | {
  /** Modulo: remainder after dividing first by second. */
  $$_expression: 'MODULO';
  args: Array<NumericExpressionArg<T, FT>>;
} | {
  /** Absolute value. */
  $$_expression: 'ABS';
  args: Array<NumericExpressionArg<T, FT>>;
} | {
  /** Ceiling: round up to nearest integer. */
  $$_expression: 'CEIL';
  args: Array<NumericExpressionArg<T, FT>>;
} | {
  /** Floor: round down to nearest integer. */
  $$_expression: 'FLOOR';
  args: Array<NumericExpressionArg<T, FT>>;
} | {
  /** Round to nearest integer. */
  $$_expression: 'ROUND';
  args: Array<NumericExpressionArg<T, FT>>;
} | {
  /** Power: raise `base` to the power of `exponent` (base^exponent). */
  $$_expression: 'POWER';
  args: {
    base: NumericExpressionArg<T, FT>;
    exponent: NumericExpressionArg<T, FT>;
  };
} | {
  /** Square root. */
  $$_expression: 'SQRT';
  args: Array<NumericExpressionArg<T, FT>>;
} | {
  /** Length: number of characters in a string. */
  $$_expression: 'LENGTH';
  args: GetColumnByType<FT, string> | string;
} | {
  /**
   * Date difference: complete time units between `from` and `to`
   * in the given unit.
   */
  $$_expression: 'DATE_DIFF';
  args: {
    from: GetColumnByType<FT, Date> | Date;
    to: GetColumnByType<FT, Date> | Date;
    unit: TimeUnit;
  };
} | {
  /**
   * Date addition: add a number of time units to a date. Negative
   * `amount` subtracts.
   */
  $$_expression: 'DATE_ADD';
  args: {
    date: GetColumnByType<FT, Date> | Date;
    amount: GetColumnByType<FT, number> | number;
    unit: TimeUnit;
  };
} | {
  /** Current timestamp (date + time). */
  $$_expression: 'NOW';
} | {
  /** Current date without the time component. */
  $$_expression: 'CURRENT_DATE';
} | {
  /** Current time without the date component. */
  $$_expression: 'CURRENT_TIME';
} | {
  /** Current timestamp — alias for `NOW`. */
  $$_expression: 'CURRENT_TIMESTAMP';
} | {
  /**
   * Current timestamp with timezone info. PostgreSQL-specific;
   * translates to `CURRENT_TIMESTAMP` elsewhere.
   */
  $$_expression: 'CURRENT_TIMESTAMPTZ';
} | {
  /**
   * UUID v4 generator. SQLite/MongoDB: generated by DAM
   * pre-query.
   */
  $$_expression: 'UUID';
} | {
  /** Concatenate multiple strings. */
  $$_expression: 'CONCAT';
  args: Array<GetColumnByType<FT, string> | string>;
} | {
  /** Lowercase. */
  $$_expression: 'LOWER';
  args: GetColumnByType<FT, string> | string;
} | {
  /** Uppercase. */
  $$_expression: 'UPPER';
  args: GetColumnByType<FT, string> | string;
} | {
  /** Trim leading and trailing whitespace. */
  $$_expression: 'TRIM';
  args: GetColumnByType<FT, string> | string;
} | {
  /** Left trim — remove leading whitespace. */
  $$_expression: 'LTRIM';
  args: GetColumnByType<FT, string> | string;
} | {
  /** Right trim — remove trailing whitespace. */
  $$_expression: 'RTRIM';
  args: GetColumnByType<FT, string> | string;
} | {
  /**
   * Substring extraction. `start` is 1-based (SQL-native). Omit
   * `length` to extract to end of string.
   */
  $$_expression: 'SUBSTR';
  args: {
    string: GetColumnByType<FT, string> | string;
    start: GetColumnByType<FT, number> | number;
    length?: GetColumnByType<FT, number> | number;
  };
} | {
  /** Replace all occurrences of `search` with `replace` in `string`. */
  $$_expression: 'REPLACE';
  args: {
    string: GetColumnByType<FT, string> | string;
    search: GetColumnByType<FT, string> | string;
    replace: GetColumnByType<FT, string> | string;
  };
} | {
  /** Pad on the left to reach `length`. Default `fill` is space. */
  $$_expression: 'LPAD';
  args: {
    string: GetColumnByType<FT, string> | string;
    length: GetColumnByType<FT, number> | number;
    fill?: GetColumnByType<FT, string> | string;
  };
} | {
  /** Pad on the right to reach `length`. Default `fill` is space. */
  $$_expression: 'RPAD';
  args: {
    string: GetColumnByType<FT, string> | string;
    length: GetColumnByType<FT, number> | number;
    fill?: GetColumnByType<FT, string> | string;
  };
} | {
  /**
   * Symmetric encryption (platform-dependent).
   *
   * - PostgreSQL: pgcrypto + AES.
   * - MariaDB: native `AES_ENCRYPT`.
   * - SQLite / MongoDB: no built-in support; stores as-is.
   *
   * For SQLite/MongoDB, encrypt at the application layer before
   * passing data to DAM if you actually need encryption.
   */
  $$_expression: 'ENCRYPT';
  args: {
    secret: keyof FT | string;
    data: keyof FT | string | number | bigint | Date | boolean;
  };
} | {
  /**
   * Symmetric decryption (platform-dependent). Only works on data
   * encrypted by the corresponding database.
   *
   * - PostgreSQL: pgcrypto + AES.
   * - MariaDB: native `AES_DECRYPT`.
   * - SQLite / MongoDB: returns value as-is.
   */
  $$_expression: 'DECRYPT';
  args: {
    secret: keyof FT | string;
    data: keyof FT | string | number | bigint | Date | boolean;
  };
} | {
  /**
   * Cryptographic hashing (platform-dependent).
   *
   * - PostgreSQL: `digest()` with configurable algorithm.
   * - MariaDB: `SHA2()`.
   * - SQLite / MongoDB: stores as-is.
   *
   * For SQLite/MongoDB, hash at the application layer.
   */
  $$_expression: 'HASH';
  args: keyof FT | string | number | bigint | Date | boolean;
};
// TODO: Complex to implement — commented out for now.
// | {
//   /**
//    * COALESCE — first non-null value. Useful for defaults.
//    */
//   $$_expression: 'COALESCE';
//   args: Array<keyof FT | string | number | bigint | Date | boolean | null>;
// } | {
//   /**
//    * NULLIF — returns NULL when both arguments are equal,
//    * otherwise returns the first. Useful for converting specific
//    * values to NULL.
//    */
//   $$_expression: 'NULLIF';
//   args: [
//     keyof FT | string | number | bigint | Date | boolean,
//     keyof FT | string | number | bigint | Date | boolean,
//   ];
// } | {
//   /**
//    * CAST — convert a value to a different type. Supported
//    * targets: STRING, NUMBER, BIGINT, DATE, BOOLEAN.
//    */
//   $$_expression: 'CAST';
//   args: {
//     value: keyof FT | string | number | bigint | Date | boolean;
//     targetType: 'STRING' | 'NUMBER' | 'BIGINT' | 'DATE' | 'BOOLEAN';
//   };
// };
