/**
 * @fileoverview The CLI — the modules generator (static-parse), the init
 * scaffold, and health end-to-end. upgrade's network bump isn't exercised
 * here (its regex is covered indirectly).
 * @module
 */
import * as asserts from '@std/asserts';
import { describe, it } from '@tundralibs/compat/test';
import { isDeno } from '@tundralibs/compat/runtime';
import {
  makeDir,
  makeTempDir,
  pathExists,
  readDir,
  readTextFile,
  removeDir,
  writeTextFile,
} from '@tundralibs/compat/file';
import { Application } from '../Application.ts';
import * as decoratorsBarrel from '../decorators/mod.ts';
import * as endpointsBarrel from '../endpoints/mod.ts';
import { RAPID_ERROR_CODES } from '../errors/mod.ts';
import * as middlewaresBarrel from '../middlewares/mod.ts';
import {
  exportedClasses,
  generateBarrel,
  modulesCommand,
} from './commands/modules.ts';
import { healthCommand } from './commands/health.ts';
import { initCommand } from './commands/init.ts';
import { MIDDLEWARE_CATALOG, PACKAGE_DOCS, scaffold } from './templates.ts';

describe('rapid.cli modules generator', () => {
  it('exportedClasses picks concrete classes and skips abstract bases', () => {
    const src = [
      'export abstract class Base extends RapidModule {}',
      'export class Users extends Base {}',
      'class Hidden {}',
      'export class Posts extends Base {}',
    ].join('\n');
    asserts.assertEquals(exportedClasses(src), ['Users', 'Posts']);
  });

  it('generateBarrel emits sorted re-exports, skipping the base, tests and mod.ts', async () => {
    const dir = await makeTempDir({ prefix: 'rapid-cli-' });
    try {
      await writeTextFile(
        `${dir}/AppModule.ts`,
        'export abstract class AppModule {}',
      );
      await writeTextFile(`${dir}/Posts.ts`, 'export class Posts {}');
      await writeTextFile(`${dir}/Users.ts`, 'export class Users {}');
      await writeTextFile(`${dir}/Users.test.ts`, 'export class Nope {}');
      // A stale barrel this command wrote earlier — the only kind it overwrites.
      await writeTextFile(
        `${dir}/mod.ts`,
        '// Generated by `rapid modules` — do not edit by hand.\nold\n',
      );
      const barrel = await generateBarrel(dir);
      asserts.assertStringIncludes(barrel, 'do not edit by hand');
      asserts.assertEquals(
        barrel.trim().split('\n').filter((l) => l.startsWith('export')),
        [
          `export { Posts } from './Posts.ts';`,
          `export { Users } from './Users.ts';`,
        ],
      );
      // write, then --check is clean; mutate → --check fails
      asserts.assertEquals(await modulesCommand(dir), 0);
      asserts.assertEquals(await modulesCommand(dir, { check: true }), 0);
      await writeTextFile(`${dir}/New.ts`, 'export class New {}');
      asserts.assertEquals(await modulesCommand(dir, { check: true }), 1);
    } finally {
      await removeDir(dir, { recursive: true });
    }
  });
});

describe('rapid.cli init scaffold', () => {
  it('scaffold() maps files by the toggles — ONE config file, by runtime', () => {
    const full = scaffold(
      {
        name: 'demo',
        module: true,
        norm: true,
        runtime: 'bun',
        docker: true,
        github: true,
      },
      '1.2.3',
    );
    for (
      const f of [
        'main.ts',
        'configs/Application.yaml',
        'package.json',
        'modules/Greeter.ts',
        'models/mod.ts',
        'db.ts',
        'Dockerfile',
        '.dockerignore',
        '.github/workflows/ci.yml',
      ]
    ) {
      asserts.assert(f in full, `missing ${f}`);
    }
    // A bun project is NOT a deno project: no deno.json alongside.
    asserts.assert(
      !('deno.json' in full),
      'bun scaffold must not emit deno.json',
    );
    asserts.assertStringIncludes(full['Dockerfile']!, 'FROM tundrasoft/bun:');
    // The image only STARTS the app — dependencies must be installed at build.
    asserts.assertStringIncludes(full['Dockerfile']!, 'RUN bun install');
    // A fresh scaffold has no test files; bun would otherwise exit 1.
    asserts.assertStringIncludes(
      full['package.json']!,
      'bun test --pass-with-no-tests',
    );
    // S6-image contract: the app is started from ENV, never a CMD/ENTRYPOINT.
    asserts.assertStringIncludes(full['Dockerfile']!, 'ENV SCRIPT=start');
    asserts.assert(
      !/^(CMD|ENTRYPOINT)/m.test(full['Dockerfile']!),
      'no CMD/ENTRYPOINT',
    );
    asserts.assertStringIncludes(
      full['package.json']!,
      '"dev": "bun --watch main.ts"',
    );
    asserts.assertStringIncludes(
      full['package.json']!,
      'tundralibs__rapid@^1.2.3',
    );
    asserts.assertStringIncludes(
      full['.github/workflows/ci.yml']!,
      'oven-sh/setup-bun',
    );
    asserts.assertStringIncludes(full['main.ts']!, 'app.modules');

    const minimal = scaffold(
      {
        name: 'bare',
        module: false,
        norm: false,
        runtime: 'deno',
        docker: false,
        github: false,
      },
      '1.0.0',
    );
    asserts.assert('deno.json' in minimal);
    asserts.assert(
      !('package.json' in minimal),
      'deno scaffold must not emit package.json',
    );
    asserts.assert(!('modules/Greeter.ts' in minimal));
    asserts.assert(!('Dockerfile' in minimal));
    asserts.assert(!('.github/workflows/ci.yml' in minimal));
    asserts.assertStringIncludes(
      minimal['deno.json']!,
      '@tundralibs/rapid@^1.0.0',
    );
    asserts.assertStringIncludes(minimal['main.ts']!, "app.get('/'");
  });

  it('scaffold() for deno Docker sets the TASK + ALLOW_* env contract', () => {
    const f = scaffold(
      {
        name: 'd',
        module: false,
        norm: false,
        runtime: 'deno',
        docker: true,
        github: true,
      },
      '1.0.0',
    );
    asserts.assertStringIncludes(f['Dockerfile']!, 'FROM tundrasoft/deno:');
    asserts.assertStringIncludes(f['Dockerfile']!, 'RUN deno install');
    asserts.assertStringIncludes(f['Dockerfile']!, 'TASK=start');
    asserts.assertStringIncludes(f['Dockerfile']!, 'ALLOW_NET=1');
    asserts.assertStringIncludes(
      f['.github/workflows/ci.yml']!,
      'denoland/setup-deno',
    );
    asserts.assertStringIncludes(
      f['.github/workflows/ci.yml']!,
      'deno test -A',
    );
  });

  it('scaffold() for node pins the image major tundrasoft/node actually publishes', () => {
    // tundrasoft/node builds the 5 newest LTS (all 24.x); only the newest gets
    // the <major> tag, so `:22` will never exist — a Dockerfile pinning it
    // would fail to pull. Pin 24, and keep setup-node in step.
    const f = scaffold(
      {
        name: 'n',
        module: false,
        norm: false,
        runtime: 'node',
        docker: true,
        github: true,
      },
      '1.0.0',
    );
    asserts.assertStringIncludes(f['Dockerfile']!, 'FROM tundrasoft/node:24');
    asserts.assertStringIncludes(f['Dockerfile']!, 'RUN npm install');
    // tsx runs the app at start time — a runtime dependency, not a dev one.
    const pkg = JSON.parse(f['package.json']!) as {
      dependencies: Record<string, string>;
      devDependencies?: Record<string, string>;
    };
    asserts.assert('tsx' in pkg.dependencies, 'tsx under dependencies');
    asserts.assertEquals(pkg.devDependencies, undefined);
    asserts.assert(
      !f['Dockerfile']!.includes('node:22'),
      'the :22 tag is never published',
    );
    asserts.assertStringIncludes(
      f['.github/workflows/ci.yml']!,
      'node-version: 24',
    );
  });

  it('the scaffolded Application.yaml BOOTS an app and documents every option rapid defaults', async () => {
    const base = await makeTempDir({ prefix: 'rapid-yaml-' });
    try {
      const yaml = scaffold(
        {
          name: 'cfgapp',
          module: false,
          norm: false,
          runtime: 'deno',
          docker: false,
          github: false,
        },
        '1.0.0',
      )['configs/Application.yaml']!;
      await makeDir(`${base}/configs`, { recursive: true });
      await writeTextFile(`${base}/configs/Application.yaml`, yaml);
      // 1. It boots: every active key is accepted and validated.
      const app = await Application.initialize({
        path: `${base}/configs`,
        env: false,
      });
      asserts.assertEquals(app.option('name'), 'cfgapp');
      asserts.assertEquals(app.option('server')!.port, 3000);
      asserts.assertEquals(app.mode, 'DEVELOPMENT');

      // 2. Drift guard: the template must document every option rapid
      // DEFAULTS. A new defaulted option fails here until the template
      // (cli/templates.ts APPLICATION_YAML) is updated — by design.
      const active = new Set<string>();
      const stack: string[] = [];
      for (const line of yaml.split('\n')) {
        const m = /^( *)([A-Za-z_]\w*):/.exec(line); // skips comments / blanks
        if (m === null) continue;
        const depth = m[1]!.length / 2;
        stack.length = depth;
        stack[depth] = m[2]!;
        active.add(stack.slice(0, depth + 1).join('.'));
      }
      const server = app.option('server')!;
      const groups: Record<string, Record<string, unknown>> = {
        server: server as Record<string, unknown>,
        'server.paging': server.paging as Record<string, unknown>,
        'server.query': server.query as Record<string, unknown>,
        'server.versioning': server.versioning as Record<string, unknown>,
        jobs: app.option('jobs') as Record<string, unknown>,
        uploads: app.option('uploads') as Record<string, unknown>,
        headers: app.option('headers') as Record<string, unknown>,
        'logger.access': {
          enabled: true,
          skip: [],
          client: false,
        } as Record<string, unknown>,
      };
      // Documented as a COMMENTED example on purpose (its default is a temp dir).
      const commentedByDesign = new Set(['uploads.path']);
      for (const [group, obj] of Object.entries(groups)) {
        for (const [key, value] of Object.entries(obj)) {
          const path = `${group}.${key}`;
          if (commentedByDesign.has(path)) continue;
          if (
            value !== null && typeof value === 'object' && !Array.isArray(value)
          ) {
            continue; // sub-groups are checked under their own entry above
          }
          asserts.assert(
            active.has(path),
            `Application.yaml template is missing \`${path}\` (rapid defaults it) — update APPLICATION_YAML in cli/templates.ts`,
          );
        }
      }
      for (const top of ['mode', 'stateMode', 'shutdownTimeout', 'logger']) {
        asserts.assert(
          active.has(top),
          `template missing top-level \`${top}\``,
        );
      }
    } finally {
      await removeDir(base, { recursive: true });
    }
  });

  it('scaffold() always emits ONE AGENTS.md source + two pointers, runtime- and module-aware', () => {
    const f = scaffold(
      {
        name: 'aiapp',
        module: true,
        norm: false,
        runtime: 'bun',
        docker: false,
        github: false,
      },
      '1.0.0',
    );
    for (
      const p of ['AGENTS.md', 'CLAUDE.md', '.github/copilot-instructions.md']
    ) {
      asserts.assert(p in f, `missing ${p}`);
    }
    const agents = f['AGENTS.md']!;
    // Single source: the pointers name AGENTS.md and carry no duplicated guidance.
    asserts.assertStringIncludes(f['CLAUDE.md']!, 'AGENTS.md');
    asserts.assertStringIncludes(
      f['.github/copilot-instructions.md']!,
      '/AGENTS.md',
    );
    asserts.assert(
      !f['CLAUDE.md']!.includes('colon-wrapped'),
      'pointer must not duplicate the guide',
    );
    // Claude Code loads the guide itself through the import line.
    asserts.assertStringIncludes(f['CLAUDE.md']!, '\n@AGENTS.md\n');
    // True for THIS project: its runtime commands, its name, its module layout.
    asserts.assertStringIncludes(agents, 'running on **bun**');
    asserts.assertStringIncludes(agents, 'bun run dev');
    asserts.assertStringIncludes(agents, '# aiapp');
    asserts.assertStringIncludes(agents, '## Modules');
    asserts.assertStringIncludes(agents, 'modules/Greeter.ts');
    // And rapid's real API facts, not generic advice.
    asserts.assertStringIncludes(agents, '/users/:id:');
    asserts.assertStringIncludes(agents, 'Application.initialize');
    asserts.assertStringIncludes(agents, 'validated()');
    asserts.assert(
      !agents.includes('deno task'),
      'bun project must not show deno commands',
    );
    // Package lookup is NEED-first (the names aren't self-describing): a table
    // row maps the job to the full specifier, and each shape leads with the job.
    asserts.assertMatch(
      agents,
      /\| Validate input[^|]*\| `@tundralibs\/guardian`/,
    );
    asserts.assertMatch(agents, /\| Authentication[^|]*\| `@tundralibs\/pact`/);
    asserts.assertStringIncludes(
      agents,
      '**Validation — `@tundralibs/guardian`.**',
    );
    asserts.assert(
      !agents.includes('- **guardian** —'),
      'shapes must lead with the job, not the bare package name',
    );

    // No module system → no Modules section; deno → deno commands.
    const plain = scaffold(
      {
        name: 'p',
        module: false,
        norm: false,
        runtime: 'deno',
        docker: false,
        github: false,
      },
      '1.0.0',
    );
    asserts.assert(!plain['AGENTS.md']!.includes('## Modules'));
    asserts.assertStringIncludes(plain['AGENTS.md']!, 'deno task test');
    // Doc links are pinned to the scaffolded version; offline (null) falls
    // back to the package page rather than inventing a version.
    asserts.assertStringIncludes(
      plain['AGENTS.md']!,
      'https://jsr.io/@tundralibs/rapid/1.0.0/docs/Rapid-Errors.md',
    );
    const offline = scaffold(
      {
        name: 'o',
        module: false,
        norm: false,
        runtime: 'node',
        docker: false,
        github: false,
      },
      null,
    )['AGENTS.md']!;
    asserts.assertStringIncludes(
      offline,
      'https://jsr.io/@tundralibs/rapid/README.md',
    );
    asserts.assertStringIncludes(offline, 'node_modules/@tundralibs/rapid/');
  });

  it('AGENTS.md drift guard: the guide names every public surface the package exports', async () => {
    const agents = scaffold(
      {
        name: 'guide',
        module: true,
        norm: false,
        runtime: 'deno',
        docker: false,
        github: false,
        ui: true,
      },
      '9.9.9',
    )['AGENTS.md']!;
    const missing = (what: string, names: readonly string[]) =>
      names.filter((n) => !agents.includes(n)).map((n) => `${what}: ${n}`);
    const functions = (barrel: Record<string, unknown>) =>
      Object.keys(barrel).filter((k) => typeof barrel[k] === 'function');
    const pkg = new URL('../', import.meta.url).pathname;
    const manifest = JSON.parse(await readTextFile(`${pkg}deno.json`)) as {
      exports: Record<string, string>;
    };
    const docs: string[] = [];
    for await (const entry of readDir(`${pkg}docs`)) {
      if (entry.name.endsWith('.md')) docs.push(`docs/${entry.name}`);
    }
    const catalogText = MIDDLEWARE_CATALOG.map(([f]) => f).join(' ');
    const gaps = [
      // every subpath a consumer can import
      ...missing(
        'subpath',
        Object.keys(manifest.exports)
          .filter((k) => k !== '.')
          .map((k) => `@tundralibs/rapid/${k.slice(2)}`),
      ),
      // every middleware factory / helper the barrel exports, in the catalog
      ...functions(middlewaresBarrel)
        .filter((n) => !catalogText.includes(n))
        .map((n) => `middleware catalog: ${n}`),
      // every decorator and binder
      ...missing('decorator/binder', functions(decoratorsBarrel)),
      // every endpoint
      ...missing('endpoint', functions(endpointsBarrel).map((n) => `${n}(`)),
      // every error code (the table is generated from the registry)
      ...missing('error code', Object.keys(RAPID_ERROR_CODES)),
      // every doc shipped in the package, linked at the installed version
      ...missing(
        'doc',
        docs.map((f) => `https://jsr.io/@tundralibs/rapid/9.9.9/${f}`),
      ),
      ...docs.filter((f) => !PACKAGE_DOCS.some(([file]) => file === f))
        .map((f) => `PACKAGE_DOCS: ${f}`),
      // every config group the annotated YAML carries
      ...missing('config group', [
        'headers',
        'server.',
        'jobs.enabled',
        'uploads',
        'logger.access',
        'tracer',
        'ui:',
      ]),
      ...missing('CLI command', [
        'init [name]',
        'upgrade',
        'modules [dir]',
        'health [url]',
      ]),
    ];
    asserts.assertEquals(
      gaps,
      [],
      'update AGENTS_MD / MIDDLEWARE_CATALOG / PACKAGE_DOCS in cli/templates.ts',
    );
  });

  it('scaffold() --ui emits the three-tier views, static+ui config, and a templated home', () => {
    const f = scaffold(
      {
        name: 'shop',
        module: true,
        norm: false,
        runtime: 'deno',
        docker: false,
        github: false,
        ui: true,
        vendorCss: 'pico.min.css',
      },
      '1.0.0',
    );
    // The three tiers + components + starter css.
    for (
      const file of [
        'views/core.ts',
        'views/layout.ts',
        'views/components.ts',
        'views/mod.ts',
        'public/site.css',
        'modules/Home.ts',
        'modules/Home.views.ts',
      ]
    ) {
      asserts.assert(file in f, `missing ${file}`);
    }
    // Config: static under server (config-dir-relative root, fingerprint)
    // and the ui data half at top level.
    const yaml = f['configs/Application.yaml']!;
    asserts.assertStringIncludes(yaml, 'static:');
    asserts.assertStringIncludes(yaml, 'root: ../public');
    asserts.assertStringIncludes(yaml, 'fingerprint: true');
    asserts.assertStringIncludes(yaml, '\nui:\n');
    asserts.assertStringIncludes(yaml, 'prefer: html');
    // main.ts wires the CODE half at initialize.
    asserts.assertStringIncludes(
      f['main.ts']!,
      'ui: { core: CoreShell, layout: PageShape }',
    );
    // The vendor stylesheet links BEFORE site.css, via view.asset.
    asserts.assertStringIncludes(
      f['views/core.ts']!,
      "view.asset('/public/vendor/pico.min.css')",
    );
    // The barrel exports both modules.
    asserts.assertStringIncludes(f['modules/mod.ts']!, 'export { Home }');
    // The home module is a templated page route.
    asserts.assertStringIncludes(f['modules/Home.ts']!, "prefer: 'html'");
  });

  it('scaffold() --ui without modules swaps the JSON sample for a templated page', () => {
    const f = scaffold(
      {
        name: 'shop',
        module: false,
        norm: false,
        runtime: 'deno',
        docker: false,
        github: false,
        ui: true,
      },
      '1.0.0',
    );
    asserts.assertStringIncludes(f['main.ts']!, 'template: { render: HomePage');
    asserts.assertEquals('modules/Home.ts' in f, false);
    // No vendor css requested -> no vendor link in the core.
    asserts.assertEquals(
      f['views/core.ts']!.includes('/public/vendor/'),
      false,
    );
  });

  it('scaffold() for workers emits wrangler.toml + worker.ts, never a Dockerfile', () => {
    const f = scaffold(
      {
        name: 'edge',
        module: true,
        norm: false,
        runtime: 'workers',
        docker: true,
        github: true,
      },
      '1.0.0',
    );
    asserts.assert('wrangler.toml' in f);
    asserts.assert('worker.ts' in f);
    asserts.assert(!('main.ts' in f), 'workers uses worker.ts, not main.ts');
    asserts.assert(
      !('Dockerfile' in f),
      'no container for workers, even with docker:true',
    );
    asserts.assertStringIncludes(
      f['worker.ts']!,
      'fetch: (request: Request) => app.fetch(request)',
    );
    asserts.assertStringIncludes(
      f['worker.ts']!,
      'app.modules({ modules: [modules] })',
    );
    asserts.assertStringIncludes(f['wrangler.toml']!, 'name = "edge"');
    asserts.assertStringIncludes(f['package.json']!, '"wrangler"');
    asserts.assertStringIncludes(
      f['.github/workflows/ci.yml']!,
      'wrangler deploy --dry-run',
    );
  });

  it('initCommand writes the project tree under a base dir (no cwd juggling)', async () => {
    const base = await makeTempDir({ prefix: 'rapid-init-' });
    try {
      const code = await initCommand(
        {
          _: ['sample'],
          module: true,
          norm: false,
          runtime: 'deno',
          docker: false,
          yes: true,
        },
        base,
      );
      asserts.assertEquals(code, 0);
      asserts.assert(await pathExists(`${base}/sample/main.ts`));
      asserts.assert(await pathExists(`${base}/sample/modules/Greeter.ts`));
      asserts.assertStringIncludes(
        await readTextFile(`${base}/sample/configs/Application.yaml`),
        'name: sample',
      );
    } finally {
      await removeDir(base, { recursive: true });
    }
  });

  it('initCommand refuses to overwrite an existing project', async () => {
    const base = await makeTempDir({ prefix: 'rapid-init-dup-' });
    try {
      const args = { _: ['twice'], yes: true };
      asserts.assertEquals(await initCommand(args, base), 0);
      // Second run into the same base with the same name hits the guard.
      asserts.assertEquals(await initCommand(args, base), 1);
    } finally {
      await removeDir(base, { recursive: true });
    }
  });

  it('initCommand rejects a name with path separators (no escape write)', async () => {
    const base = await makeTempDir({ prefix: 'rapid-init-esc-' });
    try {
      asserts.assertEquals(
        await initCommand({ _: ['../escape'], yes: true }, base),
        1,
      );
      // The guard fires before any write — base stays empty of the escape.
      asserts.assert(!(await pathExists(`${base}/../escape`)));
    } finally {
      await removeDir(base, { recursive: true });
    }
  });

  it('initCommand rejects an empty name (would write to the filesystem root)', async () => {
    const base = await makeTempDir({ prefix: 'rapid-init-empty-' });
    try {
      // A bare `""` positional skips the default and, unguarded, makes `root`
      // empty → writes at `/`. The guard must reject it.
      asserts.assertEquals(
        await initCommand({ _: [''], yes: true }, base),
        1,
      );
    } finally {
      await removeDir(base, { recursive: true });
    }
  });
});

describe('rapid.cli health', () => {
  it('reports 0 for a healthy app, 1 for a bad path', async () => {
    const app = await Application.initialize({
      name: 'cli-health',
      server: { port: 0, hostname: '127.0.0.1' },
      logger: { handlers: [] },
      uploads: { path: '/tmp/rapid-cli-health' },
    });
    app.get('/health', () => ({ content: 'ok' }));
    await app.start();
    try {
      const base = `http://127.0.0.1:${app.port}`;
      asserts.assertEquals(await healthCommand(base, { path: '/health' }), 0);
      asserts.assertEquals(await healthCommand(base, { path: '/nope' }), 1);
    } finally {
      await app.stop();
    }
  });

  it('returns 1 when the app is unreachable (fetch throws)', async () => {
    // Nothing listens on port 1 — the fetch rejects, hitting the catch.
    asserts.assertEquals(
      await healthCommand('http://127.0.0.1:1', { path: '/health' }),
      1,
    );
  });
});

describe('rapid.cli init scaffold — installable and type-correct', () => {
  const base = (over: Partial<Parameters<typeof scaffold>[0]>) =>
    scaffold(
      {
        name: 'demo',
        module: true,
        norm: true,
        runtime: 'deno',
        docker: false,
        github: false,
        ...over,
      },
      '1.2.3',
    );

  it('npm-shaped runtimes get an .npmrc pointing @jsr at npm.jsr.io; deno does not', () => {
    for (const runtime of ['bun', 'node', 'workers'] as const) {
      const f = base({ runtime });
      asserts.assertEquals(f['.npmrc'], '@jsr:registry=https://npm.jsr.io\n');
    }
    asserts.assert(!('.npmrc' in base({ runtime: 'deno' })));
  });

  it('--norm declares @tundralibs/norm in the chosen manifest, beside rapid', () => {
    asserts.assertStringIncludes(
      base({ runtime: 'deno' })['deno.json']!,
      '"@tundralibs/norm": "jsr:@tundralibs/norm@^1"',
    );
    asserts.assertStringIncludes(
      base({ runtime: 'node' })['package.json']!,
      '"@tundralibs/norm": "npm:@jsr/tundralibs__norm@^1"',
    );
    asserts.assert(!base({ norm: false })['deno.json']!.includes('norm'));
  });

  it('an unknown rapid version pins nothing (= latest) instead of a made-up floor', () => {
    const f = scaffold(
      {
        name: 'demo',
        module: false,
        norm: false,
        runtime: 'deno',
        docker: false,
        github: false,
      },
      null,
    );
    asserts.assertStringIncludes(
      f['deno.json']!,
      '"@tundralibs/rapid": "jsr:@tundralibs/rapid"',
    );
    asserts.assertStringIncludes(
      base({})['deno.json']!,
      '"@tundralibs/rapid": "jsr:@tundralibs/rapid@^1.2.3"',
    );
  });

  it({
    name:
      'a generated --module --norm project passes `deno check` and `deno lint` against the workspace',
    bun: false,
    node: false,
    fn: async () => {
      const dir = await makeTempDir({ prefix: 'rapid-scaffold-check-' });
      try {
        const files = base({ runtime: 'deno' });
        for (const [path, body] of Object.entries(files)) {
          const slash = path.lastIndexOf('/');
          if (slash > 0) {
            await makeDir(`${dir}/${path.slice(0, slash)}`, {
              recursive: true,
            });
          }
          await writeTextFile(`${dir}/${path}`, body);
        }
        // The scaffold's deno.json pins a registry version; the workspace
        // root config resolves the SAME specifiers to the local packages.
        const root = new URL('../../../', import.meta.url).pathname;
        const run = async (...args: string[]) => {
          const out = await new Deno.Command(Deno.execPath(), {
            args: [...args, '--config', `${root}deno.json`],
            cwd: dir,
            stdout: 'piped',
            stderr: 'piped',
          }).output();
          return {
            code: out.code,
            text: new TextDecoder().decode(out.stderr) +
              new TextDecoder().decode(out.stdout),
          };
        };
        const check = await run('check', 'main.ts', 'db.ts');
        asserts.assertEquals(check.code, 0, check.text);
        const lint = await run('lint', 'main.ts', 'db.ts', 'modules', 'models');
        asserts.assertEquals(lint.code, 0, lint.text);
      } finally {
        await removeDir(dir, { recursive: true });
      }
    },
  });

  it('initCommand rejects a name that would corrupt the generated YAML/JSON/TS', async () => {
    const tmp = await makeTempDir({ prefix: 'rapid-init-name-' });
    try {
      for (const name of ["it's", 'a"b', 'x: y', '-lead', 'sp ace']) {
        const code = await initCommand(
          { _: [name], module: false, norm: false, runtime: 'deno', yes: true },
          tmp,
        );
        asserts.assertEquals(code, 1, name);
        asserts.assertEquals(await pathExists(`${tmp}/${name}`), false, name);
      }
      const ok = await initCommand(
        {
          _: ['my-app.v2'],
          module: false,
          norm: false,
          runtime: 'deno',
          yes: true,
        },
        tmp,
      );
      asserts.assertEquals(ok, 0);
    } finally {
      await removeDir(tmp, { recursive: true });
    }
  });
});

describe('rapid.cli modules generator — duplicate class names', () => {
  it('two files exporting one class name fail loudly, naming both, instead of emitting a barrel that cannot compile', async () => {
    const dir = await makeTempDir({ prefix: 'rapid-barrel-dup-' });
    try {
      await writeTextFile(`${dir}/A.ts`, 'export class Users {}\n');
      await writeTextFile(`${dir}/B.ts`, 'export class Users {}\n');
      await asserts.assertRejects(
        () => generateBarrel(dir),
        Error,
        "'Users' is exported by both A.ts and B.ts",
      );
      asserts.assertEquals(await modulesCommand(dir), 1);
      asserts.assertEquals(await pathExists(`${dir}/mod.ts`), false);
    } finally {
      await removeDir(dir, { recursive: true });
    }
  });
});

describe('rapid.cli modules generator — overwrite guard', () => {
  it('refuses to overwrite a mod.ts it did not generate unless --force; a generated one is regenerated freely', async () => {
    const dir = await makeTempDir({ prefix: 'rapid-barrel-guard-' });
    try {
      await writeTextFile(`${dir}/A.ts`, 'export class Users {}\n');
      const handWritten = 'export const notABarrel = 1;\n';
      await writeTextFile(`${dir}/mod.ts`, handWritten);
      asserts.assertEquals(await modulesCommand(dir), 1);
      asserts.assertEquals(await readTextFile(`${dir}/mod.ts`), handWritten);
      asserts.assertEquals(await modulesCommand(dir, { force: true }), 0);
      const generated = await readTextFile(`${dir}/mod.ts`);
      asserts.assertStringIncludes(
        generated,
        "export { Users } from './A.ts';",
      );
      await writeTextFile(`${dir}/B.ts`, 'export class Orders {}\n');
      asserts.assertEquals(await modulesCommand(dir), 0); // generated → no --force needed
      asserts.assertStringIncludes(
        await readTextFile(`${dir}/mod.ts`),
        "export { Orders } from './B.ts';",
      );
    } finally {
      await removeDir(dir, { recursive: true });
    }
  });
});
