/**
 * @fileoverview Project templates for `rapid init`, kept as plain,
 * EDITABLE string constants — one per file. `{{token}}` placeholders are
 * filled by {@link render}. {@link scaffold} assembles the file map for a
 * given set of answers (module / norm / docker toggles). Edit the strings
 * below to change what a new project looks like.
 *
 * @module
 */

/** The choices `rapid init` gathers. */
export type ScaffoldAnswers = {
  name: string;
  module: boolean;
  norm: boolean;
  /**
   * The project's runtime — a PROJECT-WIDE choice made first: it decides
   * which config file is primary (`deno.json` vs `package.json`), the
   * install/dev/start/test commands, and the deploy artifact. `workers`
   * (Cloudflare) serves via `app.fetch` and gets `wrangler.toml` instead of
   * a Dockerfile.
   */
  runtime: 'deno' | 'bun' | 'node' | 'workers';
  /** A Dockerfile on the org `tundrasoft/<runtime>` image (deno/bun/node only). */
  docker: boolean;
  /** A GitHub Actions CI workflow (fmt / lint / check / test on the chosen runtime). */
  github: boolean;
  /**
   * AI-assistant instructions: one real `AGENTS.md` (rapid's conventions,
   * this project's runtime commands and layout) plus thin pointers
   * `CLAUDE.md` and `.github/copilot-instructions.md`, so Claude Code,
   * Cursor, Codex and Copilot all resolve to ONE source and never drift.
   */
  ai: boolean;
};

/** Replace every `{{key}}` in `tpl` from `vars`. */
export const render = (tpl: string, vars: Record<string, string>): string =>
  tpl.replace(/\{\{(\w+)\}\}/g, (_, k) => vars[k] ?? '');

// ── templates ───────────────────────────────────────────────────────────

const GITIGNORE = `node_modules/
.env
*.log
/dist/
/coverage/
.rapid-uploads/
`;

const APPLICATION_YAML = `name: {{name}}
mode: DEVELOPMENT
server:
  port: 3000
  hostname: localhost
  versioning:
    mode: header
    identifier: x-api-version
    default: v1
logger:
  level: INFO
`;

const MAIN_PLAIN = `import { Application } from '@tundralibs/rapid';

const configDir = new URL('./configs', import.meta.url).pathname;
const app = await Application.initialize(configDir);

app.get('/', () => ({ content: { app: '{{name}}', ok: true } }));

await app.start();
app.log.info(\`{{name}} listening on \${app.address}\`);
`;

const MAIN_MODULES = `import { Application } from '@tundralibs/rapid';
import * as modules from './modules/mod.ts';

const configDir = new URL('./configs', import.meta.url).pathname;
const app = await Application.initialize(configDir);

// Boot the module system — every RapidModule exported from modules/mod.ts.
await app.modules({ modules: [modules] });

await app.start();
app.log.info(\`{{name}} listening on \${app.address}\`);
`;

const MODULE_SAMPLE = `import { GET } from '@tundralibs/rapid/decorators';
import { event, RapidModule } from '@tundralibs/rapid/modules';

const EVENTS = { Greeted: event<{ name: string }>() };

export class Greeter extends RapidModule<typeof EVENTS> {
  readonly name = 'Greeter';
  readonly namespace = 'greeter';
  protected readonly events = EVENTS;

  @GET('/hello/:name:')
  async hello(name: string) {
    await this.emit('Greeted', { name });
    this.log.info('greeted', { name });
    return { content: { hello: name } };
  }
}
`;

const MODULES_BARREL = `// Generated by \`rapid modules\` — do not edit by hand.
export { Greeter } from './Greeter.ts';
`;

const DB = `import { Norm } from '@tundralibs/norm';
import { BlogSchema } from './models/mod.ts';

/** One connected Norm instance for the app (SQLite by default). */
export const norm = new Norm({
  database: { dialect: 'sqlite', path: './data' },
});
await norm.connect();
export const db = norm.use(BlogSchema);
`;

const MODEL_SAMPLE = `import { Norm } from '@tundralibs/norm';

/** A minimal norm entity — adjust to your schema. */
export const Users = {
  name: 'Users',
  columns: {
    id: { type: 'UUID', primaryKey: true },
    email: { type: 'VARCHAR', length: 255 },
    createdAt: { type: 'TIMESTAMP' },
  },
} as const;
`;

const MODELS_BARREL = `import { Users } from './Users.ts';

/** The schema registry norm.use() consumes. */
export const BlogSchema = { Users } as const;
`;

const DENO_JSON = `{
  "name": "{{name}}",
  "tasks": {
    "dev": "deno run -A --watch main.ts",
    "start": "deno run -A main.ts",
    "modules": "deno run -A jsr:@tundralibs/rapid/cli modules ./modules",
    "upgrade": "deno run -A jsr:@tundralibs/rapid/cli upgrade",
    "test": "deno test -A",
    "fmt": "deno fmt",
    "lint": "deno lint",
    "check": "deno check main.ts"
  },
  "imports": {
    "@tundralibs/rapid": "jsr:@tundralibs/rapid@^{{rapidVersion}}"
  }
}
`;

const PACKAGE_JSON = `{
  "name": "{{name}}",
  "type": "module",
  "scripts": {
    "dev": "{{devCmd}}",
    "start": "{{startCmd}}",
    "modules": "{{runTs}} node_modules/@tundralibs/rapid/cli/mod.ts modules ./modules",
    "upgrade": "{{runTs}} node_modules/@tundralibs/rapid/cli/mod.ts upgrade",
    "test": "{{testCmd}}"
  },
  "dependencies": {
    "@tundralibs/rapid": "npm:@jsr/tundralibs__rapid@^{{rapidVersion}}"
  }{{devDeps}}
}
`;

const README = `# {{name}}

A [rAPId](https://jsr.io/@tundralibs/rapid) application.

## Run

\`\`\`bash
{{runHint}}
\`\`\`

## Tasks

- \`dev\` / \`start\` — run the app
- \`modules\` — regenerate \`modules/mod.ts\`
- \`upgrade\` — bump \`@tundralibs/*\` to the latest release
`;

const DOCKERFILE =
  `# Built on the org image: Alpine + s6-overlay, runs as the unprivileged
# \`tundra\` user, and starts the app from the ENV contract below — the image's
# own s6 service runs it, so there is deliberately NO CMD / ENTRYPOINT here.
FROM tundrasoft/{{runtime}}:{{imageTag}}

COPY --chown=tundra:tundra . /app

# {{runtimeEnvDoc}}
{{runtimeEnv}}
EXPOSE {{port}}
`;

const DOCKERIGNORE = `node_modules
.git
*.log
/dist
/coverage
.env
`;

const WRANGLER_TOML = `name = "{{name}}"
main = "worker.ts"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]
`;

const WORKER_TS =
  `// Cloudflare Workers entry: no listening socket, so the app serves through
// its fetch handler. Jobs are not scheduled here — fire them from a Cron
// Trigger via app.triggerJob(); socket commands need a listener.
import { Application } from '@tundralibs/rapid';
{{workerModulesImport}}
const app = await Application.initialize({ name: '{{name}}' });
{{workerSetup}}
export default { fetch: (request: Request) => app.fetch(request) };
`;

const CI_WORKFLOW = `name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
{{ciSetup}}
{{ciSteps}}
`;

const AGENTS_MD = `# {{name}} — agent guide

A [rAPId](https://jsr.io/@tundralibs/rapid) application running on **{{runtime}}**.
This file is the always-on baseline for any AI working in this repo. It is read
by Claude Code (via \`CLAUDE.md\`), Cursor and Codex (via \`AGENTS.md\`), and GitHub
Copilot (via \`.github/copilot-instructions.md\`) — all three resolve here.

## Commands

\`\`\`bash
{{aiCommands}}
\`\`\`

Run the relevant ones before you consider a change done.

## How this app is built

- **One entry point.** \`Application.initialize(source)\` is the ONLY way to make
  an app (the constructor is private). \`main.ts\` passes the \`configs/\` directory,
  so \`configs/Application.yaml\` supplies the options and every other config
  set stays readable via \`app.config\`. Never construct \`new Application()\`.
- **Routes are radrouter-native.** Path params are COLON-WRAPPED: \`/users/:id:\`,
  never express-style \`:id\`. The five verb helpers (\`app.get\`/\`post\`/\`put\`/
  \`patch\`/\`delete\`) take optional route-scoped middleware, then the handler last.
- **A handler returns the reply.** Return \`{ content, status?, headers? }\`
  (\`content\` is a string, a plain object → JSON, a \`Uint8Array\`, or a
  \`ReadableStream\` / async iterable to stream). For HTTP replies you may also
  return \`cookies: [...]\` and \`redirect: '/path'\`; both are silently ignored
  on JOB/SOCKET transports.
- **Middleware is universal.** \`app.use(mw)\` runs on HTTP requests, socket
  frames AND job firings. Narrow with \`ctx.type\` or the \`onlyHTTP\` /
  \`guardHTTP\` scope helpers (\`guard*\` fails closed — use it for auth).
- **Errors:** throw a \`RapidError(code)\` for a known condition — the code maps
  to the HTTP status and a client-safe message. An unknown throw is an opaque
  500 by design. A \`@tundralibs/guardian\` validation failure is automatically
  a 400; wrap any OTHER validator in \`validated()\` to get the same.
- **Secrets:** the app \`secret\` option (≥ 32 chars, from the environment —
  never committed) is the one HMAC key for signed cookies, \`session()\` and
  \`csrf()\`.
{{aiModules}}
## Testing

Use \`@tundralibs/rapid/testing\`: \`client(app)\` drives routes through
\`app.fetch\` with no port (\`await api.get('/path')\` → \`{ status, body }\`);
\`harness({ modules, stub })\` boots the module system with fakes stocked into
an isolated DI container. A test must be able to FAIL — never assert something
the type-checker already proves.

## Coding conventions (the org standard, fitted to an app)

- **Naming.** Classes are \`PascalCase\`; a file exporting one class/error/type
  is named after it (\`Greeter.ts\`); helper/utility files are \`camelCase\`;
  folders are lowercase or \`kebab-case\`. A test mirrors its subject:
  \`Greeter.test.ts\`. Module-level constants are \`UPPER_SNAKE_CASE\`.
- **Privacy by prefix, not \`#\`.** \`__name\` = private to the class, \`_name\` =
  protected / internal. Never use JS \`#\` private fields (they break
  subclassing and the framework's metadata-only decorators).
- **Errors.** Put app errors under \`errors/\`, one class per scenario,
  extending a single base (rapid's \`RapidError\` with a registered code maps
  straight onto an HTTP status). A helper that DETECTS a condition throws the
  typed error; a helper that merely RUNS caller code lets errors propagate
  unwrapped.
- **Imports.** Cross-folder imports go through the folder's \`mod.ts\` barrel;
  same-folder siblings import directly. One import statement per module
  (merge value and type imports).
- **JSDoc.** Every exported symbol gets a brief first line. \`{@link}\` any
  non-built-in type in prose; \`@throws {@link ErrorType}\` on every method that
  can throw — document only real throws. No marketing sections, no restating
  what the type already says.

## Which TundraLibs package for which job

The package names are not self-describing — look the NEED up here first.
All publish to JSR under \`@tundralibs/*\` and run on every runtime. Verify a
signature in the package README (or https://jsr.io/@tundralibs/<pkg>) before
using it — do not guess.

| Need                                                      | Package                                                |
| --------------------------------------------------------- | ------------------------------------------------------ |
| Validate input / define a schema                          | \`@tundralibs/guardian\`                                 |
| Authentication (JWT, API keys, HMAC signing), permissions | \`@tundralibs/pact\`                                     |
| Database models / ORM                                     | \`@tundralibs/norm\` (+ \`drivers\` for the engine)        |
| Hand-built typed query → SQL                              | \`@tundralibs/oql\`                                      |
| Cache (memory / Redis / Memcached)                        | \`@tundralibs/cacher\`                                   |
| Generate ids (nanoid / ulid / sequence)                   | \`@tundralibs/id\`                                       |
| Hash, encrypt, sign, password hashing                     | \`@tundralibs/crypt\`                                    |
| Call an upstream REST API                                 | \`@tundralibs/restler\`                                  |
| Logging                                                   | \`@tundralibs/slogger\` (via \`app.log\`)                  |
| Cron / scheduled jobs                                     | \`@tundralibs/cronus\` (via \`@JOB\`)                      |
| Dependency injection                                      | \`@tundralibs/doctor\` (\`inject()\`, \`app.container\`)     |
| Distributed tracing                                       | \`@tundralibs/tracer\` (the \`tracer\` option)             |
| A runtime-only global (fs, env, process, fetch)           | \`@tundralibs/compat\` — never the global                |
| Error base class, config loading, memoize, IP helpers     | \`@tundralibs/utils\`                                    |
| HTTP router                                               | \`@tundralibs/radrouter\` (rapid already uses it)        |

### The shapes

- **Validation — \`@tundralibs/guardian\`.** Build a schema, \`parse\` it:
  \`Guardian.object({ id: Guardian.number().integer().positive(), email:
  Guardian.string().email(), role: Guardian.enum(['admin','user']) })\`;
  \`type User = Guardian.infer<typeof UserSchema>\`; \`UserSchema.parse(input)\`
  throws, \`safeParse\` returns \`[err, value]\`. In rapid a guardian failure is
  automatically a 400 — bind it with \`payload(UserSchema.parse)\`.
- **Auth — \`@tundralibs/pact\`.** Bitmask authorization + JWT + API keys.
  \`new PACT({ bits: { READ: 1n, EDIT: 2n }, modules: { Post: ['READ','EDIT'] },
  groupResolver, secret, issuer, expiry })\`. rapid's \`jwt(pact)\` builds an
  \`authenticate\` verify and \`permission(pact, 'Post', 'EDIT')\` an \`authorize\`
  check; the result lands in \`ctx.auth\` (read-only, set once per request).
  API keys: \`generateAPIKey()\` → \`{ id, secret, secretHash }\` (persist id +
  hash ONLY, show the secret once), \`verifyAPIKey(secret, hash)\`. HMAC over
  any content: \`pact.sign(content, key?)\` / \`pact.verify(content, sig, key?)\`.
- **ORM — \`@tundralibs/norm\`.** \`Entity('users', { id: Column.uuid(), email:
  Column.varchar(255).encrypt().hash() }, { pk: ['id'] })\` → \`Schema('Identity',
  { Users })\` → \`new Norm({ engine, secret })\` → \`norm.use(Identity)\` →
  \`db.repo('Users').insert({...})\` / \`.find(...)\`. Engines come from a
  separate install, \`@tundralibs/drivers\` (e.g. \`SQLiteEngine\`,
  \`PostgresEngine\`). Pick \`--norm\` on init to get a wired \`db.ts\`.
- **Typed queries — \`@tundralibs/oql\`.** The query object norm translates to
  SQL; use it directly only for hand-built queries: \`const q: Query<'SELECT',
  User> = { type: 'SELECT', table: 'users', columns: [...], projection: {...}
  }\`, then a translator (\`PostgresTranslator\`) renders it. Reach for \`norm\`
  first.
- **Caching — \`@tundralibs/cacher\`.** Swappable backends: \`const cache =
  Cacher.create('MEMORY', 'my-cache', { defaultExpiry: 300 })\` (or \`'REDIS'\`,
  \`'MEMCACHED'\`); \`await cache.set(key, value)\`, \`await cache.get<T>(key)\`,
  \`has\`, \`delete\`, \`clear\`. Same API across backends, so start in-memory and
  switch by config. rapid's \`rateLimit()\`/\`session()\` take any \`{ get, set }\`
  store — a cacher instance fits.
- **Ids — \`@tundralibs/id\`.** \`nanoID()\` (21-char URL-safe; \`nanoID(10,
  NUMBERS)\` for length/alphabet), \`ulid()\` (sortable), \`sequenceID()\` (a
  FACTORY: \`const seq = sequenceID(); seq()\` → a bigint, counter-based,
  crypto-free), \`ObjectID()\` (also a factory). rapid mints request ids with
  \`sequenceID\` by default — set \`Application.requestIdGenerator\` to change.
- **Crypto — \`@tundralibs/crypt\`.** Primitives, by subpath. Hashing: \`await
  sha256(data)\` / \`digest(data, { algorithm: 'SHA-384' })\` from
  \`@tundralibs/crypt/digest\`. Encryption: \`encryptAES(text, key, { mode:
  'GCM', keyLength: 256 })\` / \`decryptAES\` from \`@tundralibs/crypt/encrypt\`;
  also \`pbkdf2Hash\`/\`pbkdf2Verify\` (passwords) and \`hkdf\`. Signing:
  \`signHMAC\`/\`verifyHMAC\`, JWT sign/verify. Passwords: hash with pbkdf2,
  never store plaintext.
- **REST client — \`@tundralibs/restler\`.** A typed client base. Subclass it,
  set \`vendor\`, pass \`{ baseURL }\` to \`super\`, and expose methods built on
  \`this._makeRequest<T>({ path, method, contentType: 'JSON', payload })\`.
  Put each upstream API in its own class under e.g. \`clients/\`.
- **Foundation — \`@tundralibs/utils\`.** \`BaseError<Meta>\` (extend it for app
  errors — context-carrying, chainable); \`loadConfig({ path })\` →
  \`config.get<T>('a.b')\` (what rapid's \`Application.initialize('./configs')\`
  uses); \`memoize(fn, ttlMs)\`, \`throttle(fn, ms)\`, \`once(fn)\`; \`@Singleton\`;
  \`Options\` (the options+events base class); network helpers (\`isPublicIP\`,
  \`isInSubnet\`, \`getFreePort\`); \`envArgs\` (.env + Docker secrets).
- **Logging — \`@tundralibs/slogger\`.** The logger behind \`app.log\`; reach
  for it directly only outside the app. \`new Slogger({ appName, level:
  SyslogSeverities.INFO, handlers: [{ name: 'console', type:
  'ConsoleHandler', level, formatter: 'standard' }] })\`;
  \`logger.info('msg', { ...context })\`. Inside a handler or module use
  \`app.log\` / \`this.log\` — they carry the request id for you.
- **Router — \`@tundralibs/radrouter\`.** Already inside rapid; you normally
  don't touch it. Its grammar is why params are \`/users/:id:\`. Constructor
  options rapid passes through: \`caseSensitive\`, \`ignoreTrailingSlash\`.

## Rules

- Verify, don't assert: check a symbol or behaviour in source / the rapid docs
  before relying on it.
- Minimal diffs. No speculative abstractions, no filler comments, no restating
  what the types already say.
- Keep every runtime working: use \`@tundralibs/compat\` for filesystem /
  process / runtime access rather than a runtime-only global.
- Docs and config examples must be true — a wrong example is a bug.
`;

const CLAUDE_MD = `# {{name}}

The project guide for any AI working here lives in [\`AGENTS.md\`](./AGENTS.md) —
commands, how the app is built, testing, and the rules. Read it first. This
file exists so Claude Code finds it; do not duplicate content here.
`;

const COPILOT_MD = `# GitHub Copilot instructions

The project guide for any AI working in this codebase lives in
[\`/AGENTS.md\`](../AGENTS.md) — commands, how the app is built, testing, and
the rules. Read it first. Do not duplicate content here: this file is a
pointer so every tool (Copilot, Claude Code, Cursor, Codex) resolves to the
same single source.
`;

// ── assembly ────────────────────────────────────────────────────────────

/**
 * Everything that differs per runtime, in one table. `workers` has no Docker
 * row (no container) — it gets `wrangler.toml` + `worker.ts` instead.
 */
const RUNTIME = {
  deno: {
    configFile: 'deno.json',
    runHint: 'deno task dev',
    imageTag: '2',
    // The tundrasoft/deno image runs `deno task $TASK` under s6 as `tundra`.
    runtimeEnvDoc:
      'TASK selects the deno task the image runs; ALLOW_* map to --allow-* flags.',
    runtimeEnv:
      'ENV TASK=start \\\n    ALLOW_NET=1 \\\n    ALLOW_READ=/app \\\n    ALLOW_ENV=1',
    ciSetup:
      '      - uses: denoland/setup-deno@v2\n        with:\n          deno-version: v2.x',
    ciSteps:
      '      - run: deno fmt --check\n      - run: deno lint\n      - run: deno check main.ts\n      - run: deno test -A',
    aiCommands:
      'deno task dev        # run with reload\ndeno task test       # deno test -A\ndeno fmt && deno lint && deno check main.ts\ndeno task modules    # regenerate modules/mod.ts after adding a module',
  },
  bun: {
    configFile: 'package.json',
    runHint: 'bun run dev',
    imageTag: '1',
    runtimeEnvDoc: 'SCRIPT selects the package.json script the image runs.',
    runtimeEnv: 'ENV SCRIPT=start',
    devCmd: 'bun --watch main.ts',
    startCmd: 'bun main.ts',
    runTs: 'bun',
    testCmd: 'bun test',
    devDeps: '',
    ciSetup: '      - uses: oven-sh/setup-bun@v2',
    ciSteps: '      - run: bun install\n      - run: bun test',
    aiCommands:
      'bun install\nbun run dev          # run with reload\nbun test\nbun run modules      # regenerate modules/mod.ts after adding a module',
  },
  node: {
    configFile: 'package.json',
    runHint: 'npm run dev',
    imageTag: '24',
    runtimeEnvDoc: 'SCRIPT selects the package.json script the image runs.',
    runtimeEnv: 'ENV SCRIPT=start',
    devCmd: 'node --import tsx --watch main.ts',
    startCmd: 'node --import tsx main.ts',
    runTs: 'node --import tsx',
    testCmd: 'node --import tsx --test',
    devDeps: ',\n  "devDependencies": {\n    "tsx": "^4"\n  }',
    ciSetup:
      '      - uses: actions/setup-node@v4\n        with:\n          node-version: 24',
    ciSteps: '      - run: npm ci\n      - run: npm test',
    aiCommands:
      'npm install\nnpm run dev          # run with reload (tsx --watch)\nnpm test\nnpm run modules      # regenerate modules/mod.ts after adding a module',
  },
  workers: {
    configFile: 'package.json',
    runHint: 'npx wrangler dev',
    devCmd: 'wrangler dev',
    startCmd: 'wrangler deploy',
    runTs: 'node --import tsx',
    testCmd: 'node --import tsx --test',
    devDeps:
      ',\n  "devDependencies": {\n    "tsx": "^4",\n    "wrangler": "^4"\n  }',
    ciSetup:
      '      - uses: actions/setup-node@v4\n        with:\n          node-version: 24',
    ciSteps:
      '      - run: npm ci\n      - run: npm test\n      - run: npx wrangler deploy --dry-run',
  },
} as const;

/**
 * Build the `{ relativePath: contents }` map for a scaffold. `rapidVersion`
 * is the version `rapid init` resolved for the new project's dependency.
 * The runtime decides the primary config file (never both), the run
 * commands, and the deploy artifact.
 */
export function scaffold(
  answers: ScaffoldAnswers,
  rapidVersion: string,
): Record<string, string> {
  const rt = RUNTIME[answers.runtime];
  const vars: Record<string, string> = {
    name: answers.name,
    rapidVersion,
    runtime: answers.runtime,
    port: '3000',
    ...rt,
    workerModulesImport: answers.module
      ? "import * as modules from './modules/mod.ts';"
      : '',
    workerSetup: answers.module
      ? 'await app.modules({ modules: [modules] });'
      : "app.get('/', () => ({ content: { app: '{{name}}', ok: true } }));",
    aiModules: answers.module
      ? `
## Modules (this project uses the module system)

- A module is a class extending \`RapidModule\` in \`modules/\`, declaring
  \`name\`, \`namespace\` and \`events\`; \`modules/mod.ts\` is a GENERATED barrel
  (\`rapid modules\`) — never edit it by hand, regenerate it after adding a module.
- Route methods are decorated (\`@GET('/path/:id:')\`, \`@POST\`, …, from
  \`@tundralibs/rapid/decorators\`). Decorators are metadata-only and never
  wrap the method, so a module unit-tests with \`new Greeter().hello('x')\` and
  no server. Bind arguments with \`bind: [param('id'), payload(validate)]\`.
- A module method returns the same \`{ content }\` reply shape as a handler.
  Declared events are emitted with \`this.emit('Name', payload)\`; \`this.log\`
  is a scoped logger. See \`modules/Greeter.ts\`.
`
      : '',
  };
  const put = (tpl: string) => render(tpl, vars);
  const files: Record<string, string> = {
    '.gitignore': GITIGNORE,
    'README.md': put(README),
    'configs/Application.yaml': put(APPLICATION_YAML),
  };
  // ONE primary config file, by runtime — not both.
  if (answers.runtime === 'deno') files['deno.json'] = put(DENO_JSON);
  else files['package.json'] = put(PACKAGE_JSON);

  if (answers.runtime === 'workers') {
    files['wrangler.toml'] = put(WRANGLER_TOML);
    files['worker.ts'] = render(put(WORKER_TS), vars); // second pass: {{name}} inside workerSetup
  } else {
    files['main.ts'] = put(answers.module ? MAIN_MODULES : MAIN_PLAIN);
  }
  if (answers.module) {
    files['modules/Greeter.ts'] = MODULE_SAMPLE;
    files['modules/mod.ts'] = MODULES_BARREL;
  }
  if (answers.norm) {
    files['models/Users.ts'] = MODEL_SAMPLE;
    files['models/mod.ts'] = MODELS_BARREL;
    files['db.ts'] = DB;
  }
  if (answers.docker && answers.runtime !== 'workers') {
    files['Dockerfile'] = put(DOCKERFILE);
    files['.dockerignore'] = DOCKERIGNORE;
  }
  if (answers.github) {
    files['.github/workflows/ci.yml'] = put(CI_WORKFLOW);
  }
  if (answers.ai) {
    // ONE source (AGENTS.md) + two pointers — mirrors how tools resolve them.
    files['AGENTS.md'] = render(put(AGENTS_MD), vars); // 2nd pass: {{name}} inside aiModules
    files['CLAUDE.md'] = put(CLAUDE_MD);
    files['.github/copilot-instructions.md'] = put(COPILOT_MD);
  }
  return files;
}
