/**
 * @fileoverview Project templates for `rapid init`, kept as plain,
 * EDITABLE string constants — one per file. `{{token}}` placeholders are
 * filled by {@link render}. {@link scaffold} assembles the file map for a
 * given set of answers (module / norm / docker toggles). Edit the strings
 * below to change what a new project looks like.
 *
 * @module
 */

/** The choices `rapid init` gathers. */
export type ScaffoldAnswers = {
  name: string;
  module: boolean;
  norm: boolean;
  docker: boolean;
  /** Container base runtime — one of the org `tundrasoft/*` images. */
  runtime: 'deno' | 'bun' | 'node';
};

/** Replace every `{{key}}` in `tpl` from `vars`. */
export const render = (tpl: string, vars: Record<string, string>): string =>
  tpl.replace(/\{\{(\w+)\}\}/g, (_, k) => vars[k] ?? '');

// ── templates ───────────────────────────────────────────────────────────

const GITIGNORE = `node_modules/
.env
*.log
/dist/
/coverage/
.rapid-uploads/
`;

const APPLICATION_YAML = `name: {{name}}
mode: DEVELOPMENT
server:
  port: 3000
  hostname: localhost
  versioning:
    mode: header
    identifier: x-api-version
    default: v1
logger:
  level: INFO
`;

const MAIN_PLAIN = `import { Application } from '@tundralibs/rapid';

const configDir = new URL('./configs', import.meta.url).pathname;
const app = await Application.initialize(configDir);

app.get('/', () => ({ content: { app: '{{name}}', ok: true } }));

await app.start();
app.log.info(\`{{name}} listening on \${app.address}\`);
`;

const MAIN_MODULES = `import { Application } from '@tundralibs/rapid';
import * as modules from './modules/mod.ts';

const configDir = new URL('./configs', import.meta.url).pathname;
const app = await Application.initialize(configDir);

// Boot the module system — every RapidModule exported from modules/mod.ts.
await app.modules({ modules: [modules] });

await app.start();
app.log.info(\`{{name}} listening on \${app.address}\`);
`;

const MODULE_SAMPLE = `import { GET } from '@tundralibs/rapid/decorators';
import { event, RapidModule } from '@tundralibs/rapid/modules';

const EVENTS = { Greeted: event<{ name: string }>() };

export class Greeter extends RapidModule<typeof EVENTS> {
  readonly name = 'Greeter';
  readonly namespace = 'greeter';
  protected readonly events = EVENTS;

  @GET('/hello/:name:')
  async hello(name: string) {
    await this.emit('Greeted', { name });
    this.log.info('greeted', { name });
    return { content: { hello: name } };
  }
}
`;

const MODULES_BARREL = `// Generated by \`rapid modules\` — do not edit by hand.
export { Greeter } from './Greeter.ts';
`;

const DB = `import { Norm } from '@tundralibs/norm';
import { BlogSchema } from './models/mod.ts';

/** One connected Norm instance for the app (SQLite by default). */
export const norm = new Norm({
  database: { dialect: 'sqlite', path: './data' },
});
await norm.connect();
export const db = norm.use(BlogSchema);
`;

const MODEL_SAMPLE = `import { Norm } from '@tundralibs/norm';

/** A minimal norm entity — adjust to your schema. */
export const Users = {
  name: 'Users',
  columns: {
    id: { type: 'UUID', primaryKey: true },
    email: { type: 'VARCHAR', length: 255 },
    createdAt: { type: 'TIMESTAMP' },
  },
} as const;
`;

const MODELS_BARREL = `import { Users } from './Users.ts';

/** The schema registry norm.use() consumes. */
export const BlogSchema = { Users } as const;
`;

const DENO_JSON = `{
  "name": "{{name}}",
  "tasks": {
    "dev": "deno run -A --watch main.ts",
    "start": "deno run -A main.ts",
    "modules": "deno run -A jsr:@tundralibs/rapid/cli modules ./modules",
    "upgrade": "deno run -A jsr:@tundralibs/rapid/cli upgrade",
    "test": "deno test -A",
    "fmt": "deno fmt",
    "lint": "deno lint",
    "check": "deno check main.ts"
  },
  "imports": {
    "@tundralibs/rapid": "jsr:@tundralibs/rapid@^{{rapidVersion}}"
  }
}
`;

const PACKAGE_JSON = `{
  "name": "{{name}}",
  "type": "module",
  "scripts": {
    "dev": "node --import tsx --watch main.ts",
    "start": "node --import tsx main.ts",
    "modules": "node --import tsx node_modules/@tundralibs/rapid/cli/mod.ts modules ./modules",
    "upgrade": "node --import tsx node_modules/@tundralibs/rapid/cli/mod.ts upgrade",
    "test": "node --import tsx --test"
  },
  "dependencies": {
    "@tundralibs/rapid": "npm:@jsr/tundralibs__rapid@^{{rapidVersion}}"
  },
  "devDependencies": {
    "tsx": "^4"
  }
}
`;

const README = `# {{name}}

A [rAPId](https://jsr.io/@tundralibs/rapid) application.

## Run

\`\`\`bash
deno task dev      # or: bun run dev / npm run dev
\`\`\`

## Tasks

- \`dev\` / \`start\` — run the app
- \`modules\` — regenerate \`modules/mod.ts\`
- \`upgrade\` — bump \`@tundralibs/*\` to the latest release
`;

const DOCKERFILE = `FROM tundrasoft/{{runtime}}:latest

WORKDIR /app
COPY . .

EXPOSE 3000
CMD ["{{dockerCmd}}"]
`;

const DOCKERIGNORE = `node_modules
.git
*.log
/dist
/coverage
.env
`;

// ── assembly ────────────────────────────────────────────────────────────

const DOCKER_CMD: Record<ScaffoldAnswers['runtime'], string> = {
  deno: 'deno task start',
  bun: 'bun run start',
  node: 'npm run start',
};

/**
 * Build the `{ relativePath: contents }` map for a scaffold. `rapidVersion`
 * is the version `rapid init` resolved for the new project's dependency.
 */
export function scaffold(
  answers: ScaffoldAnswers,
  rapidVersion: string,
): Record<string, string> {
  const vars = {
    name: answers.name,
    rapidVersion,
    runtime: answers.runtime,
    dockerCmd: DOCKER_CMD[answers.runtime],
  };
  const put = (tpl: string) => render(tpl, vars);
  const files: Record<string, string> = {
    '.gitignore': GITIGNORE,
    'README.md': put(README),
    'configs/Application.yaml': put(APPLICATION_YAML),
    'deno.json': put(DENO_JSON),
    'package.json': put(PACKAGE_JSON),
    'main.ts': put(answers.module ? MAIN_MODULES : MAIN_PLAIN),
  };
  if (answers.module) {
    files['modules/Greeter.ts'] = MODULE_SAMPLE;
    files['modules/mod.ts'] = MODULES_BARREL;
  }
  if (answers.norm) {
    files['models/Users.ts'] = MODEL_SAMPLE;
    files['models/mod.ts'] = MODELS_BARREL;
    files['db.ts'] = DB;
  }
  if (answers.docker) {
    files['Dockerfile'] = put(DOCKERFILE);
    files['.dockerignore'] = DOCKERIGNORE;
  }
  return files;
}
