/**
 * @fileoverview `inject` + the {@link VialRegistry} it is typed against.
 *
 * `inject(target)` resolves a dependency three ways: by a typed
 * {@link Label} (`inject(Db)`), by the class itself (`inject(Logger)`), or
 * by a string token — the **class name** — so a consumer never has to import
 * the dependency class. The string form is typed by {@link VialRegistry},
 * which you populate by augmenting this module's interface, either by hand
 * or with `@tundralibs/doctor/build`; the label and class forms need no
 * augmentation at all.
 *
 * @module
 */

import { _ambientScope, Doctor } from './Doctor.ts';
import type { Label, Vial } from './types/mod.ts';

/**
 * Global token → type registry. Empty by default; augment it so the string
 * form of `inject` is typed. The token is the class name — or a stocked
 * label's name, if you want to reach it by string rather than by label.
 *
 * ```ts
 * // Hand-written, or generated by `@tundralibs/doctor/build`:
 * declare module '@tundralibs/doctor' {
 *   interface VialRegistry {
 *     Config: import('./Config.ts').Config;
 *   }
 * }
 * ```
 */
// deno-lint-ignore no-empty-interface
export interface VialRegistry {}

/**
 * Resolve a dependency — by {@link Label}, by class, or by string token.
 *
 * - `inject(label)` returns what `Doctor.stock` put under that label,
 *   typed by the label's `T`. No module augmentation needed.
 * - `inject(Class)` returns the registered instance of `Class`, honouring
 *   its lifecycle — a class is a value that carries its own type.
 * - `inject('Token')` resolves by name without importing anything. The
 *   token must be a key of {@link VialRegistry} and the result is typed
 *   accordingly, so typos are caught at compile time; a name not in the
 *   registry is a compile error, never `unknown`. At runtime the name
 *   reaches a prescribed class or a stocked label alike — add a label's
 *   name to `VialRegistry` if you want the string form for it, or use
 *   `inject(label)`.
 *
 * `inject` is the ONE injection primitive — there is deliberately no
 * value-supplying member decorator (Bun miscompiles those whenever a
 * file holds more than one decorated class; see
 * https://github.com/oven-sh/bun/issues/30326). The three idioms:
 *
 * ```ts
 * class Handler {
 *   // EAGER — field initializer, resolves while `new` runs.
 *   logger = inject('Logger');
 *
 *   // EAGER — constructor default parameter, same timing.
 *   constructor(private db = inject('Db')) {}
 *
 *   // LAZY — memoizing getter: resolves on first access. Use it to
 *   // break a dependency cycle, defer registration past construction,
 *   // or keep the dependency out of JSON.stringify/spread.
 *   private __audit?: Audit;
 *   get audit(): Audit {
 *     return this.__audit ??= inject('Audit', 'jobs');
 *   }
 * }
 * ```
 *
 * When `scope` is omitted, falls back to the **ambient operation scope**:
 * the `scope` of the `Doctor.dispense`/`Doctor.resolve` call currently
 * constructing an instance, if any. This is what makes both eager
 * idioms scope-aware:
 *
 * ```ts
 * Doctor.resolve(Handler, 'req-7'); // logger and db resolve under 'req-7'
 * ```
 *
 * A lazy getter runs at first ACCESS — usually outside any operation,
 * where there is no ambient scope. Name the scope explicitly in lazy
 * getters (as `'jobs'` above does): inheriting whatever operation
 * happens to be in flight at first touch would bind the memoized
 * value to a nondeterministic scope. Pair lazy getters with
 * {@link Doctor.checkup} at startup so missing registrations still
 * fail at boot.
 *
 * @param target - A {@link Label}, a registered class, or a registered
 *   class's name.
 * @param scope - Scope name, forwarded to {@link Doctor.dispense} /
 *   {@link Doctor.dispenseByName}. Defaults to the ambient operation
 *   scope when one is active.
 *
 * @throws {@link UnregisteredVialError} When nothing is registered or
 *   stocked for `target` at runtime.
 * @throws {@link ScopeRequiredError} When the entry is SCOPED and no scope
 *   was given — explicitly, or by the ambient operation.
 * @throws {@link CircularDependencyError} When two eager `inject()`
 *   initializers point at each other.
 *
 * @example
 * ```ts
 * import { label } from '@tundralibs/doctor';
 *
 * type BlogDb = { repo(name: string): unknown };
 * const Db = label<BlogDb>('Db');
 *
 * const db = inject(Db); // typed BlogDb — by the label alone
 * ```
 */
export function inject<T>(target: Vial<T> | Label<T>, scope?: string): T;
/**
 * Resolve by string token — the class name — typed by
 * {@link VialRegistry}. See the overload above for the full contract.
 */
export function inject<K extends keyof VialRegistry>(
  token: K,
  scope?: string,
): VialRegistry[K];
export function inject(
  target: Vial | Label | string,
  scope?: string,
): unknown {
  const effective = scope ?? _ambientScope();
  return typeof target === 'string'
    ? Doctor.dispenseByName(target, effective)
    : Doctor.dispense(target, effective);
}
