/**
 * @fileoverview `inject` + the {@link VialRegistry} it is typed against.
 *
 * `inject('Token')` resolves a registered vial by its token — the **class
 * name** — so a consumer never has to import the dependency class. The return
 * type comes from {@link VialRegistry}, which you populate by augmenting this
 * module's interface, either by hand or with `@tundralibs/doctor/build`.
 *
 * @module
 */

import { Doctor } from './Doctor.ts';

/**
 * Global token → type registry. Empty by default; augment it so `inject` is
 * typed. The token is the class name.
 *
 * ```ts ignore
 * // Hand-written, or generated by `@tundralibs/doctor/build`:
 * declare module '@tundralibs/doctor' {
 *   interface VialRegistry {
 *     Config: import('./Config.ts').Config;
 *   }
 * }
 * ```
 */
// deno-lint-ignore no-empty-interface
export interface VialRegistry {}

/**
 * Resolve a registered vial by its token (the class name) without importing
 * the class. The token must be a key of {@link VialRegistry} and the result is
 * typed accordingly, so typos are caught at compile time.
 *
 * The registry is empty until you augment it — run `@tundralibs/doctor/build`
 * (or hand-write the augmentation) first, otherwise every token is rejected.
 *
 * @param token - The registered class's name.
 * @param scope - Scope name, forwarded to {@link Doctor.dispenseByName}.
 *
 * @throws {@link UnregisteredVialError} When nothing is registered under
 *   `token` at runtime.
 *
 * @example
 * ```ts ignore
 * const config = inject('Config'); // typed as Config, no import needed
 * ```
 */
export function inject<K extends keyof VialRegistry>(
  token: K,
  scope?: string,
): VialRegistry[K] {
  return Doctor.dispenseByName(token as string, scope) as VialRegistry[K];
}
