import type { TranslatorConfig, Generator } from "../../types/mod.ts";

export const SQLiteTranslatorConfig: TranslatorConfig = {
  quote: {
    column: '`',
    value: '\'',
  },
  dataTypes: {
    'INT': 'INTEGER',
    'INTEGER': 'INTEGER',
    'SMALLINT': 'INTEGER',
    'TINYINT': 'INTEGER',
    'SERIAL': 'INTEGER',
    'SMALLSERIAL': 'SMALLINT',
    'BIGSERIAL': 'BIGINT',
    'BIGINT': 'BIGINT',
    'BIT': 'BOOLEAN',
    'BOOLEAN': 'BOOLEAN',
    'BINARY': 'BOOLEAN',
    'REAL': 'REAL',
    'FLOAT': 'DOUBLE',
    'DOUBLE PRECISION': 'DOUBLE',
    'DOUBLE': 'DOUBLE',
    'NUMERIC': 'NUMERIC',
    'NUMBER': 'NUMERIC',
    'DECIMAL': 'DECIMAL',
    'MONEY': 'DECIMAL',
    'CHAR': 'CHARACTER',
    'CHARACTER': 'CHARACTER',
    'VARCHAR': 'VARCHAR',
    'NVARCHAR': 'VARCHAR',
    'NCHAR': 'CHARACTER',
    'CHARACTER VARYING': 'VARCHAR',
    'DATE': 'DATE',
    'TIME': 'TIME',
    'DATETIME': 'DATETIME',
    'TIMESTAMP': 'TIMESTAMP',
    'BYTEA': 'TEXT',
    'TEXT': 'TEXT',
    'UUID': 'VARCHAR',
    'JSON': 'TEXT',
    'ARRAY': 'TEXT',
    'ARRAY_STRING': 'TEXT',
    'ARRAY_INTEGER': 'TEXT',
    'ARRAY_BIGINT': 'TEXT',
    'ARRAY_DECIMAL': 'TEXT',
    'ARRAY_BOOLEAN': 'TEXT',
    'ARRAY_DATE': 'TEXT',
    'AUTO_INCREMENT': 'INTEGER',
  },
  generators: {
    'CURRENT_DATE': '${DATE(\'now\')}',
    'CURRENT_TIME': '${TIME(\'now\')}',
    'CURRENT_DATETIME': '${datetime(\'now\')}',
    'CURRENT_TIMESTAMP': '${CURRENT_TIMESTAMP}',
    'CURRENT_MONTH': (): Date => { const date = new Date(); return new Date(date.getFullYear(), date.getMonth() + 1, 0)}, 
    'NOW': '${datetime(\'now\')}',
    'UUID': crypto.randomUUID,
    'SYS_GUID': crypto.randomUUID,
  },
};
