import type { TranslatorConfig } from '../../types/mod.ts';

export const PostgresTranslatorConfig: TranslatorConfig = {
  quote: {
    column: '"',
    value: '\'',
  },
  dataTypes: {
    'INT': 'INTEGER',
    'INTEGER': 'INTEGER',
    'SMALLINT': 'INTEGER',
    'TINYINT': 'INTEGER',
    'SERIAL': 'SERIAL',
    'SMALLSERIAL': 'SMALLSERIAL',
    'BIGSERIAL': 'BIGSERIAL',
    'BIGINT': 'BIGINT',
    'BIT': 'BOOLEAN',
    'BOOLEAN': 'BOOLEAN',
    'BINARY': 'BOOLEAN',
    'REAL': 'REAL',
    'FLOAT': 'DOUBLE PRECISION',
    'DOUBLE PRECISION': 'DOUBLE PRECISION',
    'DOUBLE': 'DOUBLE PRECISION',
    'NUMERIC': 'NUMERIC',
    'NUMBER': 'NUMERIC',
    'DECIMAL': 'DECIMAL',
    'MONEY': 'DECIMAL',
    'CHAR': 'CHARACTER',
    'CHARACTER': 'CHARACTER',
    'VARCHAR': 'VARCHAR',
    'NVARCHAR': 'VARCHAR',
    'NCHAR': 'CHARACTER',
    'CHARACTER VARYING': 'VARCHAR',
    'DATE': 'DATE',
    'TIME': 'TIME',
    'DATETIME': 'DATETIME',
    'TIMESTAMP': 'TIMESTAMPTZ',
    'BYTEA': 'BYTEA',
    'TEXT': 'TEXT',
    'UUID': 'UUID',
    'JSON': 'JSON',
    'ARRAY': 'VARCHAR[]',
    'ARRAY_STRING': 'VARCHAR[]',
    'ARRAY_INTEGER': 'INTEGER[]',
    'ARRAY_BIGINT': 'BIGINT[]',
    'ARRAY_DECIMAL': 'DECIMAL[]',
    'ARRAY_BOOLEAN': 'BOOLEAN[]',
    'ARRAY_DATE': 'DATE[]',
    'AUTO_INCREMENT': 'SERIAL',
  },
  generators: {
    'CURRENT_DATE': '${CURRENT_DATE}',
    'CURRENT_TIME': '${CURRENT_TIME}',
    'CURRENT_DATETIME': '${CURRENT_DATETIME}',
    'CURRENT_TIMESTAMP': '${CURRENT_TIMESTAMP}',
    'CURRENT_MONTH': '${CURRENT_MONTH}',
    'NOW': '${NOW()}',
    'UUID': '${GEN_RANDOM_UUID()}',
    'SYS_GUID': '${REPLACE(GEN_RANDOM_UUID()::varchar, \'-\', \'\')}',
  },
};
