/**
 * @fileoverview `rapid modules [dir]` — regenerate the modules barrel.
 * Static-parse each file for a concrete `export class X` (skipping
 * `export abstract class`, which auto-excludes bases), emit sorted
 * re-exports under a generated header. `--check` fails when stale.
 * @module
 */
import { readDir, readTextFile, writeTextFile } from '@tundralibs/compat/file';

const HEADER = '// Generated by `rapid modules` — do not edit by hand.\n';
const SKIP = /(^|\/)(mod\.ts|.*\.(test|bench)\.ts|_.*|\..*)$/;

/** Concrete (non-abstract) exported class names in `source`, in order. */
export function exportedClasses(source: string): string[] {
  const names: string[] = [];
  const re = /^export\s+(abstract\s+)?class\s+([A-Za-z_$][\w$]*)/gm;
  for (let m = re.exec(source); m !== null; m = re.exec(source)) {
    if (m[1] === undefined) names.push(m[2]!); // skip `abstract`
  }
  return names;
}

/**
 * Build the barrel text for `dir` (does not write).
 *
 * @throws {Error} when two files export a class of the same name — the
 *   barrel would be ambiguous; the message names both files.
 */
export async function generateBarrel(dir: string): Promise<string> {
  const lines: string[] = [];
  const files: string[] = [];
  for await (const entry of readDir(dir)) {
    if (entry.isFile && entry.name.endsWith('.ts') && !SKIP.test(entry.name)) {
      files.push(entry.name);
    }
  }
  files.sort((a, b) => a.localeCompare(b));
  const seen = new Map<string, string>();
  for (const file of files) {
    const classes = exportedClasses(await readTextFile(`${dir}/${file}`));
    for (const name of classes.sort((a, b) => a.localeCompare(b))) {
      // Two files exporting one class name would emit two `export { X }`
      // lines — a barrel that fails to compile. Name both offenders.
      const prior = seen.get(name);
      if (prior !== undefined) {
        throw new Error(
          `module class '${name}' is exported by both ${prior} and ${file} — rename one`,
        );
      }
      seen.set(name, file);
      lines.push(`export { ${name} } from './${file}';`);
    }
  }
  return HEADER + lines.join('\n') + (lines.length ? '\n' : '');
}

/** The `modules` command. Returns the process exit code. */
export async function modulesCommand(
  dir: string,
  opts: { check?: boolean; force?: boolean } = {},
): Promise<number> {
  let barrel: string;
  try {
    barrel = await generateBarrel(dir);
  } catch (error) {
    console.error(
      `✗ ${error instanceof Error ? error.message : String(error)}`,
    );
    return 1;
  }
  const out = `${dir}/mod.ts`;
  if (opts.check) {
    let current = '';
    try {
      current = await readTextFile(out);
    } catch { /* missing → stale */ }
    if (current !== barrel) {
      console.error(`✗ ${out} is stale — run \`rapid modules ${dir}\``);
      return 1;
    }
    console.log(`✓ ${out} is up to date`);
    return 0;
  }
  // Only a file this command wrote (or none) is overwritten: a hand-written
  // barrel — or a package's public mod.ts reached via the wrong dir — is
  // refused unless --force says so.
  let existing: string | undefined;
  try {
    existing = await readTextFile(out);
  } catch { /* missing → fine */ }
  if (
    existing !== undefined && !existing.startsWith(HEADER) &&
    opts.force !== true
  ) {
    console.error(
      `✗ ${out} exists and was not generated by \`rapid modules\` — pass --force to overwrite it`,
    );
    return 1;
  }
  await writeTextFile(out, barrel);
  console.log(`✓ wrote ${out}`);
  return 0;
}
