name: CI

on: [push, pull_request]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      -
        name: Setup
        uses: actions/checkout@v3
      -
        name: Setup Deno
        uses: denoland/setup-deno@v1.1.0
        with:
          deno-version: v1.x
      -
        name: Check formatting
        run: deno fmt --check
      -
        name: Code Analysis
        run: deno lint
      -
        name: Run tests
        run: deno test -A --coverage=cov #--doc
      -
        name: Generate coverage report
        run: deno coverage --lcov cov > cov.lcov