name: CI

on: 
  push:
  pull_request:
    branches: [ main ]

jobs:
  build: 
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      -
        name: Setup
        uses: actions/checkout@v4
      -
        name: Setup Deno
        uses: denoland/setup-deno@v1.1.3
        with:
          deno-version: v1.x
      -
        name: Check formatting
        run: deno fmt --check
      -
        name: Code Analysis
        run: deno lint
      -
        name: Run tests
        run: deno test -A --coverage=cov #--doc
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASS: postgres
      -
        name: Generate coverage report
        run: deno coverage --lcov cov > cov.lcov