name: CI

on: 
  push:
  pull_request:
    branches: [ main ]

jobs:
  build: 
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      maria:
        image: mariadb
        env:
          MARIADB_ROOT_PASSWORD: maria
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysql --password=$MARIADB_ROOT_PASSWORD -e 'show databases;'""
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      -
        name: Setup
        uses: actions/checkout@v3
      -
        name: Setup Deno
        uses: denoland/setup-deno@v1.1.2
        with:
          deno-version: v1.x
      -
        name: Check formatting
        run: deno fmt --check
      -
        name: Code Analysis
        run: deno lint
      -
        name: Run tests
        run: |
          deno test -A --coverage=cov #--doc
          
        # env:
        #   POSTGRES_HOST: localhost
        #   POSTGRES_PORT: 5432
        #   POSTGRES_USER: postgres
        #   POSTGRES_PASS: postgres
      -
        name: Generate coverage report
        run: deno coverage --lcov cov > cov.lcov