name: 'Publish Packages'

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: 'Perform a dry run (no actual publishing)'
        required: true
        default: true
        type: boolean

  push:
    paths-ignore:
      - .dockerignore
      - .gitignore
      - .github/ISSUE_TEMPLATE/*
      - .github/PULL_REQUEST_TEMPLATE*
      - '**.md'
      - ./LICENSE
  pull_request:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      id-token: write
    # Only run on push events or workflow_dispatch on main branch
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main')

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: canary

      - name: Publish (dry run)
        if: (github.event_name == 'workflow_dispatch' && github.event.inputs.dryRun == 'true') || github.ref != 'refs/heads/main' || github.event_name == 'pull_request'
        run: deno publish --dry-run

      - name: Publish
        if: (github.event_name == 'workflow_dispatch' && github.event.inputs.dryRun == 'false' && github.ref == 'refs/heads/main') || (github.event_name == 'push' && github.ref == 'refs/heads/main')
        run: deno publish
