name: 'Run Tests'

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      denoVersion:
        description: 'Deno version to run tests with'
        required: true
        default: 'v2.x'
        type: choice
        options:
          - v2.x
          - canary
      submitReports:
        description: 'Submit reports to CodeCov and SonarQube'
        required: true
        default: false
        type: boolean
  push:
    paths-ignore:
      - .dockerignore
      - .gitignore
      - .github/ISSUE_TEMPLATE/*
      - .github/PULL_REQUEST_TEMPLATE*
      - '**.md'
      - ./LICENSE
      - .vscode/*
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        deno: ${{ github.event_name == 'workflow_dispatch' && format('{0}', github.event.inputs.denoVersion) != '' && fromJSON(format('["{}"]', github.event.inputs.denoVersion)) || fromJSON('["v2.x", "canary"]') }}
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install Docker on macOS
        if: matrix.os == 'macOS-latest'
        run: brew install --cask docker

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno}}

      - name: Format
        run: deno fmt --check

      - name: Lint
        run: deno task check

      - name: Spell-check
        uses: crate-ci/typos@master
        if: matrix.os == 'ubuntu-latest'
        with:
          config: ./.github/typos.toml

  test:
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgrespw
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      maria:
        image: mariadb
        env:
          MARIADB_ROOT_PASSWORD: mariapw2
          MARIADB_USER: maria
          MARIADB_PASSWORD: mariapw
          MARIADB_DATABASE: maria
        ports:
          - 3306:3306
        options: >-
          --health-cmd="healthcheck.sh  --connect --innodb_initialized"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 5

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        deno: ${{ github.event_name == 'workflow_dispatch' && format('{0}', github.event.inputs.denoVersion) != '' && fromJSON(format('["{}"]', github.event.inputs.denoVersion)) || fromJSON('["v2.x", "canary"]') }}
        os:
          - ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          # Disabling shallow clones is recommended for improving the relevancy of reporting
          fetch-depth: 0
      
      - name: Setup LCOV
        if: matrix.os == 'ubuntu-latest' && matrix.deno == 'v2.x'
        run: sudo apt install -y lcov

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}

      - name: Run tests
        run: deno task test:run && deno task test:bench && deno coverage coverage --lcov cov --output=coverage/report.lcov
      
      - name: Collect coverage
        if: (matrix.os == 'ubuntu-latest' && matrix.deno == 'v2.x') && (github.event_name != 'workflow_dispatch' || github.event.inputs.submitReports == 'true')
        uses: codecov/codecov-action@v4
        with:
          file: coverage/report.lcov
          token: ${{ secrets.CODECOV_TOKEN }}
      
      - name: Upload test results to Codecov
        if: (matrix.os == 'ubuntu-latest' && matrix.deno == 'v2.x') && (github.event_name != 'workflow_dispatch' || github.event.inputs.submitReports == 'true')
        uses: codecov/test-results-action@v1
        with:
          files: ./test-report.xml
          token: ${{ secrets.CODECOV_TOKEN }}
      
      - name: SonarQube Scan
        if: (matrix.os == 'ubuntu-latest' && matrix.deno == 'v2.x') && (github.event_name != 'workflow_dispatch' || github.event.inputs.submitReports == 'true')
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
